//! `vsdd-context-resolvers` — per-factory WASM context resolver crate.
//!
//! Provides the `WaveContextResolver`: a `#[resolver]`-annotated function that
//! reads `.factory/wave-state.yaml` and injects `wave_context` into
//! `plugin_config` at dispatch time.
//!
//! # Architecture
//! - **Effectful entry point:** `resolve_impl` — calls `host::read_file`, then
//!   delegates to the pure layer.
//! - **Pure computation layer:** `resolve_wave_context_pure` — takes a
//!   pre-parsed `WaveState`; used by the VP-075 proptest (AC-008).
//!
//! # Panic-free guarantee
//! AC-010 / BC-4.12.004 INV1: No fallible unwrap or panic-on-error calls anywhere
//! in this crate's production source. All error paths return
//! `ResolverOutput { key: ..., value: None }`.
//!
//! # Factory-agnostic invariant
//! `factory-dispatcher` has ZERO compile-time dependency on this crate
//! (BC-1.13.001 INV1 / ADR-018). The WASM artifact is loaded dynamically.

pub mod wave_context;

pub use wave_context::{WaveContext, WaveState};

use vsdd_hook_sdk::resolver as resolver_macro;
use vsdd_hook_sdk::resolver::{ResolverInput, ResolverOutput};

/// Effectful entry point for the `wave-context` resolver.
///
/// Reads `.factory/wave-state.yaml` via `host::read_file`, parses into
/// `WaveState`, then delegates to `resolve_wave_context_pure`.
///
/// Error policy (BC-4.12.004 PC3):
/// - Missing file  → `ResolverOutput { key: "wave-context", value: None }`
/// - Malformed YAML → same
/// - No active wave → same
/// Never traps. Never panics.
///
/// The `#[resolver_macro]` attribute generates the WASM `resolve()` export
/// (gated to `#[cfg(target_arch = "wasm32")]`) and a `fn main() {}` no-op
/// (BC-4.12.002 PC5).
///
/// # Clippy allow rationale
/// The `#[allow(clippy::expect_used)]` below covers macro-emitted code in
/// the `#[cfg(target_arch = "wasm32")]` block generated by `resolver_macro`.
/// The resolver_macro generates ABI boundary serialisation code with fallible
/// deserialization that panics on failure — this is unavoidable macro output,
/// not hand-written production code. On non-wasm32 hosts (all clippy runs)
/// that block is compiled out entirely, so the allow is belt-and-suspenders
/// for future wasm32 clippy CI configurations.
#[allow(clippy::expect_used)]
#[resolver_macro]
pub fn resolve_impl(input: ResolverInput) -> ResolverOutput {
    // AC-007: use top-level `input.project_dir` (NOT `plugin_config`) per spec
    // drift note documented in wave_context_test.rs.
    let path = format!("{}/.factory/wave-state.yaml", input.project_dir);

    // Read file with bounded host call. ANY error → value: None (AC-002, AC-005).
    let bytes = match vsdd_hook_sdk::host::read_file(&path, 64 * 1024, 1000) {
        Ok(b) => b,
        Err(_) => {
            return ResolverOutput {
                key: "wave-context".to_string(),
                value: None,
            };
        }
    };

    let yaml_str = match std::str::from_utf8(&bytes) {
        Ok(s) => s,
        Err(_) => {
            return ResolverOutput {
                key: "wave-context".to_string(),
                value: None,
            };
        }
    };

    // Malformed YAML → WaveState::default() (all-None) → pure fn returns value: None.
    // unwrap_or_default() is safe — WaveState::default() is all-None, not a panic.
    let wave_state = wave_context::parse_wave_state(yaml_str).unwrap_or_default();

    resolve_wave_context_pure(&input, &wave_state)
}

/// Pure computation layer — deterministic given the same inputs (VP-075).
///
/// Does NOT call `host::read_file` or perform any I/O. Takes a pre-parsed
/// `WaveState` (the caller is responsible for file reading and parsing).
///
/// Returns `ResolverOutput { key: "wave-context", value: Some({...}) }` when
/// the `wave_state` contains an active wave with all required fields populated
/// and at least one story present. Returns `ResolverOutput { key: "wave-context",
/// value: None }` in all other cases (AC-002b, AC-003, AC-004).
///
/// Per VP-075: this function is deterministic — same `(input, wave_state)` pair
/// always produces identical output. No I/O, no randomness, no side effects.
/// Per BC-4.12.004 INV1: no fallible unwrap or panic-on-error calls.
pub fn resolve_wave_context_pure(_input: &ResolverInput, wave_state: &WaveState) -> ResolverOutput {
    // AC-002b/AC-003: any field missing OR empty stories list -> value: None.
    // AC-004: missing current_wave (wave_id) -> value: None (most conservative path).
    match (
        &wave_state.current_cycle,
        &wave_state.current_wave,
        &wave_state.stories,
    ) {
        (Some(cycle), Some(wave), Some(stories)) if !stories.is_empty() => ResolverOutput {
            key: "wave-context".to_string(),
            value: Some(serde_json::json!({
                "cycle_id": cycle,
                "wave_id": wave,
                "stories": stories,
            })),
        },
        _ => ResolverOutput {
            key: "wave-context".to_string(),
            value: None,
        },
    }
}
