//! Red Gate unit tests for validate-wave-handoff-completeness.
//!
//! Generated by test-writer for S-18.02. Every test in this file maps to an
//! acceptance criterion in S-18.02 and a postcondition or invariant in
//! BC-4.14.001 v1.13. All tests that exercise `check_handoff_completeness`,
//! `on_post_tool_use`, `extract_wave_id`, `is_epic_complete`,
//! `validate_base_fields`, or `emit_over_200_line_advisory` MUST FAIL
//! (panic with `todo!()`) until the implementer fills in the real bodies.
//!
//! The single GREEN-BY-DESIGN function `path_is_handoff` is tested once here;
//! that test PASSES against the stub (by design — BC-5.38.002).
//!
//! # Red Gate Test Table (S-18.02 v1.2 corrected)
//!
//! | Test name | AC | BC clause | Red Gate state |
//! |-----------|-----|-----------|----------------|
//! | `ac_001_non_handoff_path_noop` | AC-001 | PC4 | RED (todo!) |
//! | `ac_001_path_is_handoff_green_by_design` | AC-001 | PC4 | GREEN (implemented) |
//! | `ac_001_state_md_write_is_noop` | AC-001 | PC4 / EC-007 | RED (todo!) |
//! | `ac_002_epic_complete_valid_epic_status_continues` | AC-002 | PC2a | RED (todo!) |
//! | `ac_002_epic_complete_missing_epic_status_blocks` | AC-002 | PC2a / EC-013 | RED (todo!) |
//! | `ac_002_epic_complete_unexpected_epic_status_on_nonfinal_blocks` | AC-002 / BC INV | PC2a / EC-012 | RED (todo!) |
//! | `ac_003_wave_id_1_noop_when_not_epic_complete` | AC-003 | PC3 | RED (todo!) |
//! | `ac_004_wave_id_gt1_full_validation_all_fields_present` | AC-004 | PC7 + INV3 step 4 | RED (todo!) |
//! | `ac_004_wave_id_gt1_missing_scalar_field_blocks` | AC-004 | PC7 / EC-003 | RED (todo!) |
//! | `ac_004_empty_scalar_malformed_blocks` | AC-004 | PC7 / EC-004 | RED (todo!) |
//! | `ac_004_null_allowed_for_nullable_scalars` | AC-004 | PC7 / EC-006 | RED (todo!) |
//! | `ac_005_wave_id_absent_fails_closed` | AC-005 | PC3 + PC8 + INV3 step 5 / EC-010 | RED (todo!) |
//! | `ac_006_all_failing_fields_named_in_one_message` | AC-006 | INV2 | RED (todo!) |
//! | `ac_007_empty_list_is_valid_for_list_fields` | AC-007 | PC7 / EC-005 | RED (todo!) |
//! | `ac_007_missing_list_field_is_invalid` | AC-007 | PC7 / EC-006b | RED (todo!) |
//! | `ac_008_is_epic_complete_pure_parse` | AC-008 | INV1 | RED (todo!) |
//! | `ac_009_handoff_missing_never_emitted_by_wasm_gate` | AC-009 | INV2 | RED (todo!) |
//! | `ac_010_five_step_eval_order_step2_before_step3` | AC-010 | INV3 | RED (todo!) |
//! | `ac_011_vp083_fp32_002_wave1_epic_complete_malformed_base` | AC-011 | INV3 + VP-083 | RED (todo!) |
//! | `ac_012_body_over_200_lines_emits_advisory_but_continues` | AC-012 | PC5 + INV5 | RED (todo!) |
//! | `ac_012_emit_over_200_line_advisory_fires_on_201_lines` | AC-012 | PC5 + INV5 | RED (todo!) |
//! | `helper_extract_wave_id_returns_some_for_valid_wave` | (helper) | PC3/PC7 | RED (todo!) |
//! | `helper_extract_wave_id_returns_none_when_absent` | (helper) | PC3/PC8/INV3 step 5 | RED (todo!) |
//! | `helper_extract_wave_id_errors_on_malformed_yaml` | (helper) | EC-001 | RED (todo!) |
//! | `helper_is_epic_complete_true_when_next_wave_stories_empty` | (helper) | PC2a | RED (todo!) |
//! | `helper_is_epic_complete_false_when_next_wave_stories_nonempty` | (helper) | PC2a | RED (todo!) |
//! | `helper_validate_base_fields_happy_path` | (helper) | PC7 | RED (todo!) |
//! | `helper_validate_base_fields_reports_empty_vec_on_success` | (helper) | PC7 | RED (todo!) |
//! | `vp_081_wave_close_blocked_missing_sha_field` | VP-081 | PC7 + INV1 | RED (todo!) |
//! | `vp_081_wave_id_absent_fails_closed_full_field_list` | VP-081 | PC8 / EC-010 | RED (todo!) |
//! | `vp_083_wave_1_no_op_not_epic_complete` | VP-083 | PC3 | RED (todo!) |
//! | `vp_083_non_handoff_write_is_noop_regardless_of_wave` | VP-083 | PC4 | RED (todo!) |
//!
//! Note: test_on_error_continue_crash_is_fail_open (AC-013) lives in
//! `plugins/vsdd-factory/tests/validate-wave-handoff-completeness.bats`.
//! AC-014 (hooks-registry.toml entry) is verified by the devops-engineer
//! story task T-8, not by Rust unit tests.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use validate_wave_handoff_completeness::{
    GateContext, GateResult, check_handoff_completeness, emit_over_200_line_advisory,
    extract_wave_id, is_epic_complete, on_post_tool_use, path_is_handoff, validate_base_fields,
};
use vsdd_hook_sdk::HookResult;

// ---------------------------------------------------------------------------
// Fixtures — canonical HANDOFF.md YAML strings for use across tests.
// All fixture strings follow the ADR-026 §Decision 2 HANDOFF.md schema.
// ---------------------------------------------------------------------------

/// A complete, valid wave_id=2 HANDOFF.md covering all 9 base required fields.
/// The scalar fields are non-empty strings (or null where permitted).
/// The list fields are non-empty (valid non-EPIC-COMPLETE case).
///
/// Used by AC-004 happy path (all fields present → Continue) and VP-081/VP-083.
fn fixture_wave2_all_fields_present() -> String {
    "\
wave_id: 2
last_verified_develop_sha: abc123def456
precompact_flush_sha: aabbcc112233
factory_lock_holder: null
active_bcs:
  - BC-4.14.001
next_wave_stories:
  - id: S-19.01
    status: pending
open_decisions: []
pending_fixes: []
process_gaps: []
"
    .to_string()
}

/// A valid wave_id=3 HANDOFF.md with multiple list fields populated.
fn fixture_wave3_all_fields_present() -> String {
    "\
wave_id: 3
last_verified_develop_sha: deadbeef0102
precompact_flush_sha: null
factory_lock_holder: null
active_bcs:
  - BC-5.41.001
  - BC-4.14.001
next_wave_stories:
  - id: S-20.01
    status: pending
open_decisions:
  - id: D-500
    description: Example open decision
pending_fixes: []
process_gaps: []
"
    .to_string()
}

/// Wave_id=1 HANDOFF.md with next_wave_stories non-empty (NOT EPIC-COMPLETE).
/// Used for the wave-1 no-op test (AC-003 / VP-083).
fn fixture_wave1_not_epic_complete() -> String {
    "\
wave_id: 1
last_verified_develop_sha: 1122334455aa
precompact_flush_sha: null
factory_lock_holder: null
active_bcs: []
next_wave_stories:
  - id: S-02.01
    status: pending
open_decisions: []
pending_fixes: []
process_gaps: []
"
    .to_string()
}

/// EPIC-COMPLETE HANDOFF.md — next_wave_stories is empty, epic_status present.
/// wave_id=2 (not wave-1 single-wave case). Used for AC-002 happy path.
fn fixture_epic_complete_wave2_valid() -> String {
    "\
wave_id: 2
last_verified_develop_sha: cc112233aabb
precompact_flush_sha: null
factory_lock_holder: null
active_bcs:
  - BC-5.41.001
next_wave_stories: []
open_decisions: []
pending_fixes: []
process_gaps: []
epic_status: complete
"
    .to_string()
}

/// EPIC-COMPLETE HANDOFF.md — next_wave_stories empty, epic_status ABSENT.
/// Used for AC-002 missing epic_status test (EC-013).
fn fixture_epic_complete_wave2_missing_epic_status() -> String {
    "\
wave_id: 2
last_verified_develop_sha: cc112233aabb
precompact_flush_sha: null
factory_lock_holder: null
active_bcs:
  - BC-5.41.001
next_wave_stories: []
open_decisions: []
pending_fixes: []
process_gaps: []
"
    .to_string()
}

/// Non-EPIC-COMPLETE HANDOFF.md with epic_status present (forbidden on non-final wave).
/// next_wave_stories is non-empty → this is a non-final wave.
/// Used for EC-012 (UnexpectedEpicStatus).
fn fixture_non_epic_complete_with_unexpected_epic_status() -> String {
    "\
wave_id: 2
last_verified_develop_sha: 99aabbccddee
precompact_flush_sha: null
factory_lock_holder: null
active_bcs: []
next_wave_stories:
  - id: S-19.01
    status: pending
open_decisions: []
pending_fixes: []
process_gaps: []
epic_status: complete
"
    .to_string()
}

/// wave_id=1 + EPIC-COMPLETE (next_wave_stories: []) + epic_status: complete.
/// All 9 base fields valid. Used for single-wave EPIC-COMPLETE happy path (EC-015).
fn fixture_wave1_epic_complete_valid_epic_status() -> String {
    "\
wave_id: 1
last_verified_develop_sha: 0011223344ff
precompact_flush_sha: null
factory_lock_holder: null
active_bcs: []
next_wave_stories: []
open_decisions: []
pending_fixes: []
process_gaps: []
epic_status: complete
"
    .to_string()
}

/// wave_id=1 + EPIC-COMPLETE + epic_status: complete + last_verified_develop_sha is empty string.
/// This is the VP-083 F-P32-002 DISCRIMINATING fixture for AC-011.
/// The gate must enter EPIC-COMPLETE branch (step 2) before wave-1 no-op (step 3).
/// Empty `last_verified_develop_sha` is malformed (BC-4.14.001 PC7 / EC-004).
/// Expected: Block with HandoffIncomplete (base field malformed).
fn fixture_vp083_discriminating_wave1_epic_complete_malformed_base() -> String {
    "\
wave_id: 1
last_verified_develop_sha: \"\"
precompact_flush_sha: null
factory_lock_holder: null
active_bcs: []
next_wave_stories: []
open_decisions: []
pending_fixes: []
process_gaps: []
epic_status: complete
"
    .to_string()
}

/// HANDOFF.md with wave_id=2 and last_verified_develop_sha MISSING.
/// All other fields present. Used for AC-004 single-field-missing test (EC-003).
fn fixture_wave2_missing_sha() -> String {
    "\
wave_id: 2
precompact_flush_sha: null
factory_lock_holder: null
active_bcs: []
next_wave_stories:
  - id: S-19.01
    status: pending
open_decisions: []
pending_fixes: []
process_gaps: []
"
    .to_string()
}

/// HANDOFF.md with wave_id=2 and last_verified_develop_sha present but empty string.
/// Empty string is malformed per BC-4.14.001 PC7 / EC-004.
fn fixture_wave2_empty_sha() -> String {
    "\
wave_id: 2
last_verified_develop_sha: \"\"
precompact_flush_sha: null
factory_lock_holder: null
active_bcs: []
next_wave_stories:
  - id: S-19.01
    status: pending
open_decisions: []
pending_fixes: []
process_gaps: []
"
    .to_string()
}

/// HANDOFF.md with wave_id=2 and precompact_flush_sha: null (permitted nullable).
fn fixture_wave2_null_precompact_sha() -> String {
    "\
wave_id: 2
last_verified_develop_sha: aabbccddeeff
precompact_flush_sha: null
factory_lock_holder: null
active_bcs: []
next_wave_stories:
  - id: S-19.01
    status: pending
open_decisions: []
pending_fixes: []
process_gaps: []
"
    .to_string()
}

/// HANDOFF.md with wave_id=2 and active_bcs: [] (empty list — VALID per PC7).
fn fixture_wave2_empty_list_field() -> String {
    "\
wave_id: 2
last_verified_develop_sha: aabb1122ccdd
precompact_flush_sha: null
factory_lock_holder: null
active_bcs: []
next_wave_stories:
  - id: S-19.01
    status: pending
open_decisions: []
pending_fixes: []
process_gaps: []
"
    .to_string()
}

/// HANDOFF.md with wave_id=2 and active_bcs FIELD ABSENT (invalid — missing list field).
fn fixture_wave2_missing_list_field() -> String {
    "\
wave_id: 2
last_verified_develop_sha: aabb1122ccdd
precompact_flush_sha: null
factory_lock_holder: null
next_wave_stories:
  - id: S-19.01
    status: pending
open_decisions: []
pending_fixes: []
process_gaps: []
"
    .to_string()
}

/// HANDOFF.md with wave_id=2 and multiple fields missing.
/// Missing: last_verified_develop_sha, active_bcs, open_decisions.
/// Used for AC-006 (all failing fields in one message / INV2).
fn fixture_wave2_multiple_missing_fields() -> String {
    "\
wave_id: 2
precompact_flush_sha: null
factory_lock_holder: null
next_wave_stories:
  - id: S-19.01
    status: pending
pending_fixes: []
process_gaps: []
"
    .to_string()
}

/// HANDOFF.md with wave_id field ABSENT (not wave_id: null — key is absent).
/// Used for AC-005 fail-closed test (EC-010).
fn fixture_wave_id_absent() -> String {
    "\
last_verified_develop_sha: abc123def456
precompact_flush_sha: null
factory_lock_holder: null
active_bcs: []
next_wave_stories:
  - id: S-19.01
    status: pending
open_decisions: []
pending_fixes: []
process_gaps: []
"
    .to_string()
}

/// Valid wave_id=2 HANDOFF.md with a body exceeding 200 lines.
/// Pads with comment lines after all required fields are present.
/// Used for AC-012 (over-200-line advisory — gate continues normally).
fn fixture_wave2_over_200_lines() -> String {
    let mut s = fixture_wave2_all_fields_present();
    // Add filler comment lines to push past 200 total lines.
    // fixture_wave2_all_fields_present() has ~13 lines; add 190 more.
    for i in 1..=190 {
        s.push_str(&format!("# filler line {i}\n"));
    }
    s
}

// ---------------------------------------------------------------------------
// Helper: construct a non-HANDOFF.md GateContext for no-op path (PC4).
// ---------------------------------------------------------------------------

fn make_non_handoff_ctx(file_path: &str) -> GateContext {
    GateContext {
        is_first_wave: false,
        file_path: file_path.to_string(),
        handoff_content: None, // non-HANDOFF.md → no content needed
        close_wave_mode: false,
    }
}

// ---------------------------------------------------------------------------
// Helper: construct a HANDOFF.md GateContext for wave_id > 1.
// ---------------------------------------------------------------------------

fn make_handoff_ctx(is_first_wave: bool, content: String) -> GateContext {
    GateContext {
        is_first_wave,
        file_path: "factory-artifacts/HANDOFF.md".to_string(),
        handoff_content: Some(content),
        close_wave_mode: false,
    }
}

// ---------------------------------------------------------------------------
// AC-001 — Non-HANDOFF.md path is a no-op (BC-4.14.001 PC4 / VP-083 §2)
// ---------------------------------------------------------------------------

/// AC-001 / PC4: check_handoff_completeness returns Continue when the file
/// path does NOT end with HANDOFF.md. No YAML parsing occurs.
/// Red Gate: panics at todo!() in check_handoff_completeness.
#[test]
fn ac_001_non_handoff_path_noop() {
    let ctx = make_non_handoff_ctx("factory-artifacts/wave-state.yaml");
    let result = check_handoff_completeness(&ctx);
    assert_eq!(
        result,
        GateResult::Continue,
        "AC-001/PC4: non-HANDOFF.md path must return Continue (no-op)"
    );
}

/// AC-001 / PC4 GREEN-BY-DESIGN: path_is_handoff returns true iff the path
/// ends with HANDOFF.md (case-sensitive). This test PASSES against the stub.
#[test]
fn ac_001_path_is_handoff_green_by_design() {
    // Positive cases
    assert!(
        path_is_handoff("factory-artifacts/HANDOFF.md"),
        "factory-artifacts/HANDOFF.md must match"
    );
    assert!(path_is_handoff("HANDOFF.md"), "bare HANDOFF.md must match");
    assert!(
        path_is_handoff("/some/deep/path/HANDOFF.md"),
        "deep path must match"
    );
    // Negative cases — wrong suffix
    assert!(
        !path_is_handoff("factory-artifacts/STATE.md"),
        "STATE.md must NOT match"
    );
    assert!(
        !path_is_handoff("factory-artifacts/handoff.md"),
        "lowercase handoff.md must NOT match (case-sensitive)"
    );
    assert!(
        !path_is_handoff("HANDOFF.md.bak"),
        "HANDOFF.md.bak must NOT match"
    );
    assert!(!path_is_handoff(""), "empty string must NOT match");
}

/// AC-001 / EC-007: PostToolUse Write on STATE.md is a non-HANDOFF.md path → no-op.
/// Red Gate: panics at todo!() in check_handoff_completeness.
#[test]
fn ac_001_state_md_write_is_noop() {
    let ctx = make_non_handoff_ctx("factory-artifacts/STATE.md");
    let result = check_handoff_completeness(&ctx);
    assert_eq!(
        result,
        GateResult::Continue,
        "AC-001/EC-007: STATE.md write must return Continue (non-HANDOFF.md no-op)"
    );
}

// ---------------------------------------------------------------------------
// AC-002 — EPIC-COMPLETE detection and epic_status validation (BC-4.14.001 PC2a)
// ---------------------------------------------------------------------------

/// AC-002 / PC2a / EC-014: EPIC-COMPLETE context (next_wave_stories: []) with
/// epic_status: complete present and all base fields valid → Continue.
/// Red Gate: panics at todo!() in check_handoff_completeness.
#[test]
fn ac_002_epic_complete_valid_epic_status_continues() {
    let ctx = make_handoff_ctx(false, fixture_epic_complete_wave2_valid());
    let result = check_handoff_completeness(&ctx);
    assert_eq!(
        result,
        GateResult::Continue,
        "AC-002/PC2a: EPIC-COMPLETE with valid epic_status must return Continue"
    );
}

/// AC-002 / PC2a / EC-013: EPIC-COMPLETE context with epic_status ABSENT →
/// gate blocks with MissingEpicStatus (exit 2).
/// Red Gate: panics at todo!() in check_handoff_completeness.
#[test]
fn ac_002_epic_complete_missing_epic_status_blocks() {
    let ctx = make_handoff_ctx(false, fixture_epic_complete_wave2_missing_epic_status());
    let result = check_handoff_completeness(&ctx);
    assert!(
        matches!(
            result,
            GateResult::Block {
                code: "MissingEpicStatus",
                ..
            }
        ),
        "AC-002/PC2a/EC-013: EPIC-COMPLETE missing epic_status must block with MissingEpicStatus, got: {result:?}"
    );
}

/// AC-002 / PC2a / EC-012: non-EPIC-COMPLETE wave with unexpected epic_status →
/// gate blocks with UnexpectedEpicStatus.
/// next_wave_stories is non-empty → non-final wave → epic_status is forbidden.
/// Red Gate: panics at todo!() in check_handoff_completeness.
#[test]
fn ac_002_epic_complete_unexpected_epic_status_on_nonfinal_blocks() {
    let ctx = make_handoff_ctx(
        false,
        fixture_non_epic_complete_with_unexpected_epic_status(),
    );
    let result = check_handoff_completeness(&ctx);
    assert!(
        matches!(
            result,
            GateResult::Block {
                code: "UnexpectedEpicStatus",
                ..
            }
        ),
        "AC-002/PC2a/EC-012: non-final wave with epic_status present must block with \
        UnexpectedEpicStatus, got: {result:?}"
    );
}

// ---------------------------------------------------------------------------
// AC-003 — wave_id == 1 AND NOT EPIC-COMPLETE → no-op (BC-4.14.001 PC3)
// ---------------------------------------------------------------------------

/// AC-003 / PC3 / EC-001: wave_id=1, next_wave_stories non-empty (NOT EPIC-COMPLETE) →
/// gate returns Continue (wave-1 no-op). No field validation occurs.
/// Red Gate: panics at todo!() in check_handoff_completeness.
#[test]
fn ac_003_wave_id_1_noop_when_not_epic_complete() {
    let ctx = GateContext {
        is_first_wave: true,
        file_path: "factory-artifacts/HANDOFF.md".to_string(),
        handoff_content: Some(fixture_wave1_not_epic_complete()),
        close_wave_mode: false,
    };
    let result = check_handoff_completeness(&ctx);
    assert_eq!(
        result,
        GateResult::Continue,
        "AC-003/PC3: wave_id=1 NOT EPIC-COMPLETE must return Continue (wave-1 no-op)"
    );
}

// ---------------------------------------------------------------------------
// AC-004 — wave_id > 1 → full validation of all 9 base fields (BC-4.14.001 PC7 / INV3 step 4)
// ---------------------------------------------------------------------------

/// AC-004 / PC7 / INV3 step 4: wave_id=2, all 9 base fields present and valid →
/// Continue. VP-081 postcondition C coverage.
/// Red Gate: panics at todo!() in check_handoff_completeness.
#[test]
fn ac_004_wave_id_gt1_full_validation_all_fields_present() {
    let ctx = make_handoff_ctx(false, fixture_wave2_all_fields_present());
    let result = check_handoff_completeness(&ctx);
    assert_eq!(
        result,
        GateResult::Continue,
        "AC-004/PC7: wave_id=2 all fields present must return Continue"
    );
}

/// AC-004 / PC7 / EC-003: wave_id=2, last_verified_develop_sha ABSENT →
/// block with HandoffIncomplete naming last_verified_develop_sha.
/// Red Gate: panics at todo!() in check_handoff_completeness.
#[test]
fn ac_004_wave_id_gt1_missing_scalar_field_blocks() {
    let ctx = make_handoff_ctx(false, fixture_wave2_missing_sha());
    let result = check_handoff_completeness(&ctx);
    assert!(
        matches!(
            result,
            GateResult::Block {
                code: "HandoffIncomplete",
                ..
            }
        ),
        "AC-004/PC7/EC-003: missing last_verified_develop_sha must block with \
        HandoffIncomplete, got: {result:?}"
    );
    // The block message must name the failing field.
    if let GateResult::Block { message, .. } = &result {
        assert!(
            message.contains("last_verified_develop_sha"),
            "HandoffIncomplete block message must name 'last_verified_develop_sha', got: {message}"
        );
    }
}

/// AC-004 / PC7 / EC-004: wave_id=2, last_verified_develop_sha is empty string →
/// block with HandoffIncomplete (empty scalar = malformed per BC-4.14.001 PC7).
/// Red Gate: panics at todo!() in check_handoff_completeness.
#[test]
fn ac_004_empty_scalar_malformed_blocks() {
    let ctx = make_handoff_ctx(false, fixture_wave2_empty_sha());
    let result = check_handoff_completeness(&ctx);
    assert!(
        matches!(
            result,
            GateResult::Block {
                code: "HandoffIncomplete",
                ..
            }
        ),
        "AC-004/PC7/EC-004: empty string on scalar field must block with HandoffIncomplete, \
        got: {result:?}"
    );
    if let GateResult::Block { message, .. } = &result {
        assert!(
            message.contains("last_verified_develop_sha"),
            "HandoffIncomplete block message must name 'last_verified_develop_sha', got: {message}"
        );
    }
}

/// AC-004 / PC7 / EC-006: wave_id=2, precompact_flush_sha: null → Continue.
/// null is permitted for precompact_flush_sha and factory_lock_holder (nullable scalars).
/// Red Gate: panics at todo!() in check_handoff_completeness.
#[test]
fn ac_004_null_allowed_for_nullable_scalars() {
    let ctx = make_handoff_ctx(false, fixture_wave2_null_precompact_sha());
    let result = check_handoff_completeness(&ctx);
    assert_eq!(
        result,
        GateResult::Continue,
        "AC-004/PC7/EC-006: null for precompact_flush_sha must return Continue (null is valid)"
    );
}

// ---------------------------------------------------------------------------
// AC-005 — wave_id absent → fail-closed (BC-4.14.001 PC3 + PC8 + INV3 step 5)
// ---------------------------------------------------------------------------

/// AC-005 / PC3+PC8+INV3 step 5 / EC-010: wave_id field is ABSENT from payload →
/// gate FAILS CLOSED. Must block with HandoffIncomplete naming wave_id.
/// Absent wave_id is NOT treated as wave-1 (is_first_wave=false).
/// VP-081 postcondition E coverage.
/// Red Gate: panics at todo!() in check_handoff_completeness.
#[test]
fn ac_005_wave_id_absent_fails_closed() {
    let ctx = GateContext {
        is_first_wave: false, // absent wave_id → is_first_wave=false (fail-closed)
        file_path: "factory-artifacts/HANDOFF.md".to_string(),
        handoff_content: Some(fixture_wave_id_absent()),
        close_wave_mode: false,
    };
    let result = check_handoff_completeness(&ctx);
    assert!(
        matches!(
            result,
            GateResult::Block {
                code: "HandoffIncomplete",
                ..
            }
        ),
        "AC-005/PC3+PC8+INV3-step5/EC-010: absent wave_id must block (fail-closed), \
        got: {result:?}"
    );
    if let GateResult::Block { message, .. } = &result {
        assert!(
            message.contains("wave_id"),
            "HandoffIncomplete block message must name 'wave_id' when it is absent, \
            got: {message}"
        );
    }
}

// ---------------------------------------------------------------------------
// AC-006 — All failing fields named in one message (BC-4.14.001 INV2)
// ---------------------------------------------------------------------------

/// AC-006 / INV2: when multiple fields are missing, the single HandoffIncomplete
/// block message names ALL failing fields. Not one message per field.
/// fixture_wave2_multiple_missing_fields omits: last_verified_develop_sha, active_bcs,
/// open_decisions (3 missing fields → all must appear in the message).
/// Red Gate: panics at todo!() in check_handoff_completeness.
#[test]
fn ac_006_all_failing_fields_named_in_one_message() {
    let ctx = make_handoff_ctx(false, fixture_wave2_multiple_missing_fields());
    let result = check_handoff_completeness(&ctx);
    assert!(
        matches!(
            result,
            GateResult::Block {
                code: "HandoffIncomplete",
                ..
            }
        ),
        "AC-006/INV2: multiple missing fields must produce HandoffIncomplete block, \
        got: {result:?}"
    );
    if let GateResult::Block { message, .. } = &result {
        // All 3 missing fields must appear in the single message (INV2).
        assert!(
            message.contains("last_verified_develop_sha"),
            "Block message must name 'last_verified_develop_sha', got: {message}"
        );
        assert!(
            message.contains("active_bcs"),
            "Block message must name 'active_bcs', got: {message}"
        );
        assert!(
            message.contains("open_decisions"),
            "Block message must name 'open_decisions', got: {message}"
        );
    }
}

// ---------------------------------------------------------------------------
// AC-007 — Scalar vs list field distinction (BC-4.14.001 PC7)
// ---------------------------------------------------------------------------

/// AC-007 / PC7 / EC-005: active_bcs: [] (empty list) is VALID for a list field.
/// The gate must NOT flag an empty list as malformed.
/// Red Gate: panics at todo!() in check_handoff_completeness.
#[test]
fn ac_007_empty_list_is_valid_for_list_fields() {
    let ctx = make_handoff_ctx(false, fixture_wave2_empty_list_field());
    let result = check_handoff_completeness(&ctx);
    assert_eq!(
        result,
        GateResult::Continue,
        "AC-007/PC7/EC-005: active_bcs:[] (empty list) must return Continue (empty list is valid)"
    );
}

/// AC-007 / PC7: active_bcs field ABSENT → invalid (missing list field).
/// The key must be present even if the value is an empty list.
/// Red Gate: panics at todo!() in check_handoff_completeness.
#[test]
fn ac_007_missing_list_field_is_invalid() {
    let ctx = make_handoff_ctx(false, fixture_wave2_missing_list_field());
    let result = check_handoff_completeness(&ctx);
    assert!(
        matches!(
            result,
            GateResult::Block {
                code: "HandoffIncomplete",
                ..
            }
        ),
        "AC-007/PC7: absent list field 'active_bcs' must block with HandoffIncomplete, \
        got: {result:?}"
    );
    if let GateResult::Block { message, .. } = &result {
        assert!(
            message.contains("active_bcs"),
            "Block message must name 'active_bcs' as the missing list field, got: {message}"
        );
    }
}

// ---------------------------------------------------------------------------
// AC-008 — Pure-parse invariant (BC-4.14.001 INV1)
// ---------------------------------------------------------------------------

/// AC-008 / INV1: is_epic_complete operates on the in-memory YAML string only.
/// This test drives is_epic_complete directly to verify it is a pure function:
/// no error on a valid YAML string that has next_wave_stories: [].
/// Red Gate: panics at todo!() in is_epic_complete.
#[test]
fn ac_008_is_epic_complete_pure_parse() {
    // Supplying a YAML string with next_wave_stories: [] — should detect EPIC-COMPLETE.
    let yaml = "next_wave_stories: []\n";
    let result = is_epic_complete(yaml);
    assert!(
        result.is_ok(),
        "is_epic_complete must not error on valid YAML"
    );
    assert!(
        result.unwrap(),
        "is_epic_complete must return true when next_wave_stories is empty list"
    );
}

// ---------------------------------------------------------------------------
// AC-009 — HandoffMissing NEVER emitted by WASM gate (BC-4.14.001 INV2)
// ---------------------------------------------------------------------------

/// AC-009 / INV2: the WASM gate never emits a block with code "HandoffMissing".
/// HandoffMissing is a shell-side error (BC-5.41.001 PC9); the WASM gate is
/// only triggered when the file IS present. Verify that the block codes in our
/// gate are "HandoffIncomplete", "MissingEpicStatus", or "UnexpectedEpicStatus"
/// only — never "HandoffMissing".
///
/// This test drives check_handoff_completeness with a maximally incomplete payload
/// (only wave_id present, 8 fields missing) to force a block, then asserts the
/// code is NOT "HandoffMissing".
/// Red Gate: panics at todo!() in check_handoff_completeness.
#[test]
fn ac_009_handoff_missing_never_emitted_by_wasm_gate() {
    // Minimal YAML: only wave_id present (>1 to trigger full validation), all else missing.
    let yaml = "wave_id: 2\n";
    let ctx = GateContext {
        is_first_wave: false,
        file_path: "factory-artifacts/HANDOFF.md".to_string(),
        handoff_content: Some(yaml.to_string()),
        close_wave_mode: false,
    };
    let result = check_handoff_completeness(&ctx);
    // Must produce a block.
    assert!(
        matches!(result, GateResult::Block { .. }),
        "AC-009: gate with 8 missing fields must produce a Block, got: {result:?}"
    );
    // The block code must NEVER be "HandoffMissing".
    if let GateResult::Block { code, .. } = &result {
        assert_ne!(
            *code, "HandoffMissing",
            "AC-009/INV2: WASM gate must never emit 'HandoffMissing' block code — \
            HandoffMissing is a shell-side error (BC-5.41.001 PC9)"
        );
    }
}

// ---------------------------------------------------------------------------
// AC-010 — 5-step evaluation order: step 2 (EPIC-COMPLETE) before step 3 (wave_id==1)
// ---------------------------------------------------------------------------

/// AC-010 / INV3: the canonical 5-step evaluation order is enforced.
/// Specifically: step 2 (EPIC-COMPLETE detection) PRECEDES step 3 (wave_id==1 no-op).
///
/// Single-wave EPIC-COMPLETE scenario (EC-015): wave_id=1 + next_wave_stories: []
/// + epic_status: complete + all base fields valid → Continue.
/// If the gate evaluated wave_id==1 as step 2 (wrong order), it would return Continue
/// without checking epic_status. Both outcomes here are Continue, but the gate must
/// have validated epic_status (proven by ac_011 discriminating fixture below).
///
/// This test covers the happy-path ordering: single-wave EPIC-COMPLETE with all fields
/// valid and epic_status present → Continue (EC-015).
/// Red Gate: panics at todo!() in check_handoff_completeness.
#[test]
fn ac_010_five_step_eval_order_step2_before_step3() {
    // wave_id=1 + EPIC-COMPLETE + epic_status: complete + all base fields valid.
    // Step 2 (EPIC-COMPLETE) fires before step 3 (wave-1 no-op).
    // With all fields valid → Continue (EP-015 single-wave EPIC-COMPLETE happy path).
    let ctx = GateContext {
        is_first_wave: true,
        file_path: "factory-artifacts/HANDOFF.md".to_string(),
        handoff_content: Some(fixture_wave1_epic_complete_valid_epic_status()),
        close_wave_mode: false,
    };
    let result = check_handoff_completeness(&ctx);
    assert_eq!(
        result,
        GateResult::Continue,
        "AC-010/INV3: single-wave EPIC-COMPLETE (wave_id=1 + next_wave_stories:[]) with \
        valid epic_status must return Continue (EC-015); step 2 checked before step 3"
    );
}

// ---------------------------------------------------------------------------
// AC-011 — VP-083 F-P32-002 discriminating fixture (INV3 + VP-083 v1.9/v1.10)
// ---------------------------------------------------------------------------

/// AC-011 / INV3 / VP-083 F-P32-002: DISCRIMINATING fixture proving EPIC-COMPLETE
/// branch (step 2 per BC-4.14.001 INV3) fires BEFORE the wave-1 no-op (step 3).
///
/// Setup: wave_id=1 + next_wave_stories: [] (EPIC-COMPLETE) + epic_status: complete
/// (present and valid) + last_verified_develop_sha: "" (empty string — malformed
/// per BC-4.14.001 PC7 / EC-004).
///
/// Expected: Block with HandoffIncomplete (empty last_verified_develop_sha is malformed).
///
/// Why this is discriminating (VP-083 F-P32-002): if the gate short-circuited on the
/// wave-1 no-op (step 3) before reaching EPIC-COMPLETE + full validation, it would
/// return Continue instead of Block. A Block result is a direct witness that:
///   (a) the gate DID NOT short-circuit on wave-1 no-op, AND
///   (b) the EPIC-COMPLETE branch (step 2) was entered and full base-field validation ran.
///
/// This fixture corroborates BC-4.14.001 PC7/EC-004 (F-P32-001): empty scalar = malformed.
/// Red Gate: panics at todo!() in check_handoff_completeness.
#[test]
fn ac_011_vp083_fp32_002_wave1_epic_complete_malformed_base() {
    let ctx = GateContext {
        is_first_wave: true,
        file_path: "factory-artifacts/HANDOFF.md".to_string(),
        handoff_content: Some(fixture_vp083_discriminating_wave1_epic_complete_malformed_base()),
        close_wave_mode: false,
    };
    let result = check_handoff_completeness(&ctx);
    assert!(
        matches!(
            result,
            GateResult::Block {
                code: "HandoffIncomplete",
                ..
            }
        ),
        "AC-011/INV3/VP-083-F-P32-002: Expected HandoffIncomplete block — gate must enter \
        EPIC-COMPLETE branch (step 2) and run full base-field validation. Empty \
        last_verified_develop_sha is malformed (EC-004). If gate returned Continue, it \
        short-circuited on wave-1 no-op (step 3) — evaluation order violation per \
        BC-4.14.001 INV3. Got: {result:?}"
    );
    // The block message must name last_verified_develop_sha as the malformed field.
    if let GateResult::Block { message, .. } = &result {
        assert!(
            message.contains("last_verified_develop_sha"),
            "HandoffIncomplete block must name 'last_verified_develop_sha' as the malformed field, \
            got: {message}"
        );
    }
}

// ---------------------------------------------------------------------------
// AC-012 — Over-200-line advisory: gate continues, advisory emitted (PC5 + INV5)
// ---------------------------------------------------------------------------

/// AC-012 / PC5 / INV5: when HANDOFF.md body exceeds 200 lines, the gate emits
/// a plugin.log advisory warn but continues (does NOT block).
/// The over-200-line cap is advisory only; the gate still validates all fields.
/// The fixture has >200 lines AND all 9 fields valid → Continue.
/// Red Gate: panics at todo!() in check_handoff_completeness.
#[test]
fn ac_012_body_over_200_lines_emits_advisory_but_continues() {
    let content = fixture_wave2_over_200_lines();
    // Sanity: fixture must exceed 200 lines.
    let line_count = content.lines().count();
    assert!(
        line_count > 200,
        "test fixture must exceed 200 lines, got {line_count} lines"
    );
    let ctx = make_handoff_ctx(false, content);
    let result = check_handoff_completeness(&ctx);
    assert_eq!(
        result,
        GateResult::Continue,
        "AC-012/PC5/INV5: over-200-line HANDOFF.md with all valid fields must return Continue \
        (advisory-only, no hard fail on length), got: {result:?}"
    );
}

/// AC-012 / PC5 / INV5: emit_over_200_line_advisory accepts a line count and
/// returns normally (side-effect-only advisory helper — no panic, no block).
/// The correct green behavior is to call `host::log_warn` and return `()`.
/// Because `host::log_warn` side effects are not observable in a Rust unit test,
/// asserting clean return (no panic, no value) is the appropriate assertion here.
/// The behavioral block/continue coverage is already carried by
/// `ac_012_body_over_200_lines_emits_advisory_but_continues`, which goes through
/// `check_handoff_completeness` and asserts `GateResult::Continue`.
/// Red Gate: panics at todo!() in emit_over_200_line_advisory.
#[test]
fn ac_012_emit_over_200_line_advisory_fires_on_201_lines() {
    // When correctly implemented, this must return without panicking.
    // Calling with a value clearly above the 200-line threshold (AC-012/PC5/INV5).
    emit_over_200_line_advisory(201);
    // If we reach here, the function returned normally — correct behavior.
    // Also exercise a boundary value above the cap.
    emit_over_200_line_advisory(350);
}

// ---------------------------------------------------------------------------
// Helper function tests — extract_wave_id (PC3/PC8/INV3 step 5)
// ---------------------------------------------------------------------------

/// Helper / PC3: extract_wave_id returns Some(n) for a valid integer wave_id field.
/// Red Gate: panics at todo!() in extract_wave_id.
#[test]
fn helper_extract_wave_id_returns_some_for_valid_wave() {
    let yaml = "wave_id: 3\nlast_verified_develop_sha: abc\n";
    let result = extract_wave_id(yaml);
    assert!(
        result.is_ok(),
        "extract_wave_id must not error on valid YAML"
    );
    assert_eq!(
        result.unwrap(),
        Some(3),
        "extract_wave_id must return Some(3) for wave_id: 3"
    );
}

/// Helper / PC3+PC8+INV3-step5: extract_wave_id returns None when wave_id field is absent.
/// Absent wave_id → fail-closed path (not wave-1 no-op).
/// Red Gate: panics at todo!() in extract_wave_id.
#[test]
fn helper_extract_wave_id_returns_none_when_absent() {
    let yaml = "last_verified_develop_sha: abc\n";
    let result = extract_wave_id(yaml);
    assert!(
        result.is_ok(),
        "extract_wave_id must not error when field absent"
    );
    assert_eq!(
        result.unwrap(),
        None,
        "extract_wave_id must return None when wave_id key is absent"
    );
}

/// Helper / EC-001: extract_wave_id returns Err on malformed YAML (parse error).
/// Red Gate: panics at todo!() in extract_wave_id.
#[test]
fn helper_extract_wave_id_errors_on_malformed_yaml() {
    let yaml = "wave_id: [not an int\n"; // malformed YAML
    let result = extract_wave_id(yaml);
    assert!(
        result.is_err(),
        "extract_wave_id must return Err on malformed YAML, got: {result:?}"
    );
}

// ---------------------------------------------------------------------------
// Helper function tests — is_epic_complete (PC2a)
// ---------------------------------------------------------------------------

/// Helper / PC2a: is_epic_complete returns true when next_wave_stories is empty list.
/// Red Gate: panics at todo!() in is_epic_complete.
#[test]
fn helper_is_epic_complete_true_when_next_wave_stories_empty() {
    let yaml = "next_wave_stories: []\n";
    let result = is_epic_complete(yaml);
    assert!(
        result.is_ok(),
        "is_epic_complete must not error on valid YAML"
    );
    assert!(
        result.unwrap(),
        "is_epic_complete must return true for next_wave_stories: []"
    );
}

/// Helper / PC2a: is_epic_complete returns false when next_wave_stories is non-empty.
/// Red Gate: panics at todo!() in is_epic_complete.
#[test]
fn helper_is_epic_complete_false_when_next_wave_stories_nonempty() {
    let yaml = "next_wave_stories:\n  - id: S-02.01\n    status: pending\n";
    let result = is_epic_complete(yaml);
    assert!(
        result.is_ok(),
        "is_epic_complete must not error on valid YAML"
    );
    assert!(
        !result.unwrap(),
        "is_epic_complete must return false when next_wave_stories is non-empty"
    );
}

// ---------------------------------------------------------------------------
// Helper function tests — validate_base_fields (PC7)
// ---------------------------------------------------------------------------

/// Helper / PC7: validate_base_fields returns an empty Vec when all 9 base
/// required fields are present and valid (non-EPIC-COMPLETE mode).
/// Red Gate: panics at todo!() in validate_base_fields.
#[test]
fn helper_validate_base_fields_happy_path() {
    let yaml = fixture_wave2_all_fields_present();
    let result = validate_base_fields(&yaml, false);
    assert!(
        result.is_ok(),
        "validate_base_fields must not error on valid YAML"
    );
    assert!(
        result.unwrap().is_empty(),
        "validate_base_fields must return empty Vec when all fields are valid"
    );
}

/// Helper / PC7: validate_base_fields returns an empty Vec on a different valid fixture.
/// Verifies it handles wave_id=3 and different content without false positives.
/// Red Gate: panics at todo!() in validate_base_fields.
#[test]
fn helper_validate_base_fields_reports_empty_vec_on_success() {
    let yaml = fixture_wave3_all_fields_present();
    let result = validate_base_fields(&yaml, false);
    assert!(
        result.is_ok(),
        "validate_base_fields must not error on wave_id=3 valid YAML"
    );
    let failing = result.unwrap();
    assert!(
        failing.is_empty(),
        "validate_base_fields must return empty Vec on wave_id=3 all-fields-present fixture, \
        got: {failing:?}"
    );
}

// ---------------------------------------------------------------------------
// VP-081 — Wave Cannot Close Without Verified Handoff (wave_id > 1)
// (BC-4.14.001 PC7 + INV1 / integration-level unit coverage)
// ---------------------------------------------------------------------------

/// VP-081 Postcondition B: wave_id=2 + last_verified_develop_sha MISSING →
/// block with HandoffIncomplete. The gate blocks incomplete HANDOFF.md writes.
/// Red Gate: panics at todo!() in check_handoff_completeness.
#[test]
fn vp_081_wave_close_blocked_missing_sha_field() {
    let ctx = make_handoff_ctx(false, fixture_wave2_missing_sha());
    let result = check_handoff_completeness(&ctx);
    assert!(
        matches!(
            result,
            GateResult::Block {
                code: "HandoffIncomplete",
                ..
            }
        ),
        "VP-081/PostconditionB: wave_id=2 with missing sha must block, got: {result:?}"
    );
}

/// VP-081 Postcondition E: wave_id ABSENT from payload → gate FAILS CLOSED.
/// Blocks with HandoffIncomplete: ["wave_id"] (and any other missing fields).
/// Absent wave_id is NOT treated as wave-1 — no Continue fallback.
/// Red Gate: panics at todo!() in check_handoff_completeness.
#[test]
fn vp_081_wave_id_absent_fails_closed_full_field_list() {
    // Payload with wave_id absent AND last_verified_develop_sha absent.
    // Both should appear in the HandoffIncomplete field list.
    let yaml = "\
precompact_flush_sha: null
factory_lock_holder: null
active_bcs: []
next_wave_stories:
  - id: S-19.01
    status: pending
open_decisions: []
pending_fixes: []
process_gaps: []
";
    let ctx = GateContext {
        is_first_wave: false,
        file_path: "factory-artifacts/HANDOFF.md".to_string(),
        handoff_content: Some(yaml.to_string()),
        close_wave_mode: false,
    };
    let result = check_handoff_completeness(&ctx);
    assert!(
        matches!(
            result,
            GateResult::Block {
                code: "HandoffIncomplete",
                ..
            }
        ),
        "VP-081/PostconditionE: absent wave_id must block (fail-closed), got: {result:?}"
    );
    if let GateResult::Block { message, .. } = &result {
        assert!(
            message.contains("wave_id"),
            "HandoffIncomplete block must name 'wave_id', got: {message}"
        );
        assert!(
            message.contains("last_verified_develop_sha"),
            "HandoffIncomplete block must name 'last_verified_develop_sha', got: {message}"
        );
    }
}

// ---------------------------------------------------------------------------
// VP-083 — Completeness Gate Is No-Op on Wave-1 or Non-HANDOFF.md Writes
// (BC-4.14.001 PC3 / PC4)
// ---------------------------------------------------------------------------

/// VP-083 §1 (conditional wave-1 no-op): wave_id=1 + NOT EPIC-COMPLETE → Continue.
/// Even with a HANDOFF.md write, the gate no-ops on wave-1 when not EPIC-COMPLETE.
/// Red Gate: panics at todo!() in check_handoff_completeness.
#[test]
fn vp_083_wave_1_no_op_not_epic_complete() {
    let ctx = GateContext {
        is_first_wave: true,
        file_path: "factory-artifacts/HANDOFF.md".to_string(),
        handoff_content: Some(fixture_wave1_not_epic_complete()),
        close_wave_mode: false,
    };
    let result = check_handoff_completeness(&ctx);
    assert_eq!(
        result,
        GateResult::Continue,
        "VP-083/§1: wave_id=1 + NOT EPIC-COMPLETE + HANDOFF.md write must return Continue \
        (wave-1 no-op)"
    );
}

/// VP-083 §2 (non-HANDOFF.md write, wave-agnostic): non-HANDOFF.md target → Continue
/// at any wave including wave > 1 (PC4 check precedes wave_id evaluation per INV3 step 1).
/// Red Gate: panics at todo!() in check_handoff_completeness.
#[test]
fn vp_083_non_handoff_write_is_noop_regardless_of_wave() {
    // wave_id > 1 context, but path is not HANDOFF.md → no-op.
    let ctx = GateContext {
        is_first_wave: false,
        file_path: "factory-artifacts/lessons.md".to_string(),
        handoff_content: None,
        close_wave_mode: false,
    };
    let result = check_handoff_completeness(&ctx);
    assert_eq!(
        result,
        GateResult::Continue,
        "VP-083/§2: non-HANDOFF.md write must return Continue regardless of wave, \
        got: {result:?}"
    );
}

// ---------------------------------------------------------------------------
// F-002 (BLOCKER) — wave_id:0 and wave_id:-1 must block (BC-4.14.001 v1.15 PC7 + EC-017 + story EC-002)
//
// Current bug: validate_field checks `as_i64().is_some()`, which returns
// Some(0) for wave_id:0 and Some(-1) for wave_id:-1, so both incorrectly
// pass through as valid. Per BC-4.14.001 PC7 / EC-017 / story EC-002,
// wave_id must be a POSITIVE integer (>= 1). Zero and negative values are
// malformed and must produce Block { code: "HandoffIncomplete" }.
// ---------------------------------------------------------------------------

/// F-002 / BC-4.14.001 PC7+EC-017: wave_id: 0 in a wave>1 context (is_first_wave=false)
/// must block with HandoffIncomplete. The block message must mention "wave_id".
///
/// RED GATE: current impl uses `as_i64().is_some()` for wave_id validation,
/// which accepts 0 as a valid integer — returns Continue instead of Block.
#[test]
fn test_BC_4_14_001_wave_id_zero_blocks_handoff_incomplete() {
    let yaml = "\
wave_id: 0
last_verified_develop_sha: abc123def456
precompact_flush_sha: null
factory_lock_holder: null
active_bcs:
  - BC-4.14.001
next_wave_stories:
  - id: S-19.01
    status: pending
open_decisions: []
pending_fixes: []
process_gaps: []
";
    // wave_id=0 cannot be the first wave (0 is not a positive integer), so
    // is_first_wave=false (fail-closed). The gate must treat wave_id:0 as malformed.
    let ctx = GateContext {
        is_first_wave: false,
        file_path: "factory-artifacts/HANDOFF.md".to_string(),
        handoff_content: Some(yaml.to_string()),
        close_wave_mode: false,
    };
    let result = check_handoff_completeness(&ctx);
    assert!(
        matches!(
            result,
            GateResult::Block {
                code: "HandoffIncomplete",
                ..
            }
        ),
        "F-002/PC7/EC-017: wave_id:0 must block with HandoffIncomplete (zero is not a \
        positive integer); current impl returns Continue because as_i64().is_some() \
        accepts 0. Got: {result:?}"
    );
    if let GateResult::Block { message, .. } = &result {
        assert!(
            message.contains("wave_id"),
            "HandoffIncomplete block message must name 'wave_id' as the malformed field, \
            got: {message}"
        );
    }
}

/// F-002 / BC-4.14.001 PC7+EC-017: wave_id: -1 must block with HandoffIncomplete.
/// Negative wave_id is not a positive integer and must be rejected.
///
/// RED GATE: current impl uses `as_i64().is_some()` which accepts -1.
#[test]
fn test_BC_4_14_001_wave_id_negative_one_blocks_handoff_incomplete() {
    let yaml = "\
wave_id: -1
last_verified_develop_sha: deadbeef0102
precompact_flush_sha: null
factory_lock_holder: null
active_bcs: []
next_wave_stories:
  - id: S-19.01
    status: pending
open_decisions: []
pending_fixes: []
process_gaps: []
";
    let ctx = GateContext {
        is_first_wave: false,
        file_path: "factory-artifacts/HANDOFF.md".to_string(),
        handoff_content: Some(yaml.to_string()),
        close_wave_mode: false,
    };
    let result = check_handoff_completeness(&ctx);
    assert!(
        matches!(
            result,
            GateResult::Block {
                code: "HandoffIncomplete",
                ..
            }
        ),
        "F-002/PC7/EC-017: wave_id:-1 must block with HandoffIncomplete (negative is not a \
        positive integer); current impl accepts -1 via as_i64().is_some(). Got: {result:?}"
    );
    if let GateResult::Block { message, .. } = &result {
        assert!(
            message.contains("wave_id"),
            "HandoffIncomplete block message must name 'wave_id' for negative value, \
            got: {message}"
        );
    }
}

// ---------------------------------------------------------------------------
// F-003 (MAJOR) — path_is_handoff must use path-component-strict matching,
// not bare ends_with("HANDOFF.md").
//
// Current bug: `file_path.ends_with("HANDOFF.md")` also matches:
//   - "foo/MY-HANDOFF.md"   (suffix matches because ends_with is substring-level)
//   - "xHANDOFF.md"         (single char prefix, file name component != HANDOFF.md)
//   - "foo/WAVE-HANDOFF.md" (file name = WAVE-HANDOFF.md, not HANDOFF.md)
//   - "MYHANDOFF.md"        (no separator between prefix and HANDOFF.md)
//
// The correct implementation must check that the LAST PATH COMPONENT (file name)
// is exactly "HANDOFF.md", using std::path::Path::file_name().
// ---------------------------------------------------------------------------

/// F-003 / BC-4.14.001 PC4: path_is_handoff must NOT match "xHANDOFF.md".
/// The file name component is "xHANDOFF.md", which is not exactly "HANDOFF.md".
///
/// RED GATE: current `ends_with("HANDOFF.md")` returns true for this input.
#[test]
fn test_BC_4_14_001_path_is_handoff_xhandoff_does_not_match() {
    assert!(
        !path_is_handoff("xHANDOFF.md"),
        "F-003/PC4: 'xHANDOFF.md' must NOT match — file name is 'xHANDOFF.md', not \
        'HANDOFF.md'. Current ends_with returns true (false positive). Bug: path-component \
        match required per BC-4.14.001 PC4."
    );
}

/// F-003 / BC-4.14.001 PC4: path_is_handoff must NOT match "foo/MY-HANDOFF.md".
/// The file name component is "MY-HANDOFF.md", not "HANDOFF.md".
///
/// RED GATE: current `ends_with("HANDOFF.md")` returns true (MY-HANDOFF.md ends with HANDOFF.md).
#[test]
fn test_BC_4_14_001_path_is_handoff_my_handoff_does_not_match() {
    assert!(
        !path_is_handoff("foo/MY-HANDOFF.md"),
        "F-003/PC4: 'foo/MY-HANDOFF.md' must NOT match — file name is 'MY-HANDOFF.md', not \
        'HANDOFF.md'. Current ends_with returns true (false positive). Bug: path-component \
        match required per BC-4.14.001 PC4."
    );
}

/// F-003 / BC-4.14.001 PC4: path_is_handoff must NOT match "foo/WAVE-HANDOFF.md".
/// The file name component is "WAVE-HANDOFF.md", not "HANDOFF.md".
///
/// RED GATE: current `ends_with("HANDOFF.md")` returns true.
#[test]
fn test_BC_4_14_001_path_is_handoff_wave_handoff_does_not_match() {
    assert!(
        !path_is_handoff("foo/WAVE-HANDOFF.md"),
        "F-003/PC4: 'foo/WAVE-HANDOFF.md' must NOT match — file name is 'WAVE-HANDOFF.md'. \
        Current ends_with returns true (false positive). Bug: path-component match required."
    );
}

/// F-003 positive regression: canonical paths that SHOULD match still match.
/// These must continue to pass after the path-component fix.
///
/// This test verifies no regression in the positive path.
/// It currently passes against the stub (GREEN-BY-DESIGN for positive cases).
#[test]
fn test_BC_4_14_001_path_is_handoff_canonical_paths_still_match() {
    assert!(
        path_is_handoff("factory-artifacts/HANDOFF.md"),
        "factory-artifacts/HANDOFF.md must match"
    );
    assert!(path_is_handoff("HANDOFF.md"), "bare HANDOFF.md must match");
    assert!(
        path_is_handoff("/some/deep/path/HANDOFF.md"),
        "/some/deep/path/HANDOFF.md must match"
    );
    assert!(
        path_is_handoff("foo/HANDOFF.md"),
        "foo/HANDOFF.md must match"
    );
}

// ---------------------------------------------------------------------------
// F-005 (MAJOR) — VP-081 integration harness tests driving on_post_tool_use
// end-to-end with a full HookPayload.
//
// These tests call on_post_tool_use (the WASM gate entry point) with
// constructed HookPayload objects and assert on HookResult, exercising the
// full Write/Edit dispatch path.
//
// Note on Edit payload (F-001 related): on_post_tool_use currently extracts
// content from tool_input["new_string"] for Edit calls. This is a fragment,
// not the full file — the correct fix requires host::read_file. Since the
// non-WASM stub always returns CapabilityDenied for host::read_file, the
// test for the Edit full-file acquisition path (F-001) cannot be validated
// in pure Rust unit tests without a host shim. See F-001 route-back below.
// The integration tests here cover Write payloads (tool_input["content"])
// and confirm the gate logic end-to-end.
// ---------------------------------------------------------------------------

/// VP-081 proof-harness skeleton: test_wave_close_blocked_missing_sha_field.
///
/// Drives on_post_tool_use with a Write payload for HANDOFF.md where
/// wave_id=2 but last_verified_develop_sha is absent. Gate must block.
///
/// RED GATE: passes if check_handoff_completeness is fully implemented.
/// Fails against any stub / todo!() in the gate chain.
#[test]
fn test_wave_close_blocked_missing_sha_field() {
    let yaml = "\
wave_id: 2
precompact_flush_sha: null
factory_lock_holder: null
active_bcs: []
next_wave_stories:
  - id: S-19.01
    status: pending
open_decisions: []
pending_fixes: []
process_gaps: []
";
    let payload = make_write_payload("factory-artifacts/HANDOFF.md", yaml);
    let result = on_post_tool_use(payload);
    assert!(
        matches!(result, HookResult::Block { .. }),
        "VP-081/test_wave_close_blocked_missing_sha_field: Write HANDOFF.md with wave_id=2 \
        and missing last_verified_develop_sha must produce Block. Got: {result:?}"
    );
    if let HookResult::Block { reason } = &result {
        assert!(
            reason.contains("HandoffIncomplete") || reason.contains("last_verified_develop_sha"),
            "Block reason must mention HandoffIncomplete or last_verified_develop_sha, got: {reason}"
        );
    }
}

/// VP-081 proof-harness skeleton: test_wave_close_allowed_with_complete_handoff.
///
/// Drives on_post_tool_use with a Write payload for HANDOFF.md where
/// wave_id=2 and all 9 required fields are present. Gate must Continue.
///
/// RED GATE: currently passes (all 9 fields valid → Continue). But this test
/// also validates the full on_post_tool_use dispatch path.
#[test]
fn test_wave_close_allowed_with_complete_handoff() {
    let yaml = "\
wave_id: 2
last_verified_develop_sha: abc123def456
precompact_flush_sha: null
factory_lock_holder: null
active_bcs:
  - BC-4.14.001
next_wave_stories:
  - id: S-19.01
    status: pending
open_decisions: []
pending_fixes: []
process_gaps: []
";
    let payload = make_write_payload("factory-artifacts/HANDOFF.md", yaml);
    let result = on_post_tool_use(payload);
    assert_eq!(
        result,
        HookResult::Continue,
        "VP-081/test_wave_close_allowed_with_complete_handoff: Write HANDOFF.md with wave_id=2 \
        and all 9 fields present must return Continue. Got: {result:?}"
    );
}

/// VP-081 proof-harness skeleton: test_wave_1_no_op.
///
/// Drives on_post_tool_use with a Write payload for HANDOFF.md where
/// wave_id=1 and next_wave_stories is non-empty (NOT EPIC-COMPLETE).
/// Gate must return Continue (wave-1 no-op per BC-4.14.001 PC3).
///
/// RED GATE: currently passes (wave-1 no-op is implemented).
#[test]
fn test_wave_1_no_op() {
    let yaml = "\
wave_id: 1
last_verified_develop_sha: 1122334455aa
precompact_flush_sha: null
factory_lock_holder: null
active_bcs: []
next_wave_stories:
  - id: S-02.01
    status: pending
open_decisions: []
pending_fixes: []
process_gaps: []
";
    let payload = make_write_payload("factory-artifacts/HANDOFF.md", yaml);
    let result = on_post_tool_use(payload);
    assert_eq!(
        result,
        HookResult::Continue,
        "VP-081/test_wave_1_no_op: Write HANDOFF.md with wave_id=1 (NOT EPIC-COMPLETE) \
        must return Continue (wave-1 no-op per BC-4.14.001 PC3). Got: {result:?}"
    );
}

/// VP-081 proof-harness skeleton: test_wave_id_absent_fails_closed.
///
/// Drives on_post_tool_use with a Write payload for HANDOFF.md where
/// wave_id field is absent from the payload. Gate must fail closed (Block).
/// Absent wave_id is NOT treated as wave-1 per BC-4.14.001 PC3/PC8/EC-010.
///
/// RED GATE: currently passes (fail-closed is implemented for absent wave_id).
#[test]
fn test_wave_id_absent_fails_closed() {
    let yaml = "\
last_verified_develop_sha: abc123def456
precompact_flush_sha: null
factory_lock_holder: null
active_bcs: []
next_wave_stories:
  - id: S-19.01
    status: pending
open_decisions: []
pending_fixes: []
process_gaps: []
";
    let payload = make_write_payload("factory-artifacts/HANDOFF.md", yaml);
    let result = on_post_tool_use(payload);
    assert!(
        matches!(result, HookResult::Block { .. }),
        "VP-081/test_wave_id_absent_fails_closed: Write HANDOFF.md with wave_id absent \
        must produce Block (fail-closed per BC-4.14.001 PC3/PC8/EC-010). Got: {result:?}"
    );
    if let HookResult::Block { reason } = &result {
        assert!(
            reason.contains("HandoffIncomplete") || reason.contains("wave_id"),
            "Block reason must mention HandoffIncomplete or wave_id, got: {reason}"
        );
    }
}

// ---------------------------------------------------------------------------
// Helper: construct a Write-tool HookPayload for a given HANDOFF.md path and content.
// ---------------------------------------------------------------------------

fn make_write_payload(file_path: &str, content: &str) -> vsdd_hook_sdk::HookPayload {
    let json = serde_json::json!({
        "event_name": "PostToolUse",
        "tool_name": "Write",
        "session_id": "integration-test-session",
        "dispatcher_trace_id": "integration-test-trace",
        "tool_input": {
            "file_path": file_path,
            "content": content
        },
        "tool_response": {
            "exit_code": 0
        }
    });
    serde_json::from_value(json).expect("HookPayload fixture must deserialize")
}
