#!/usr/bin/env bash
# tests/helpers/registry.bash — shared assertions for hooks-registry.toml.
#
# As of v1.0.0-rc.8, bats suites assert against `hooks-registry.toml`
# (the canonical, human-edited source of truth for what hooks the
# dispatcher loads) rather than `hooks/hooks.json` (per-machine,
# generated by /vsdd-factory:activate copying the right
# hooks.json.<platform> variant). The pre-rc.8 pattern of asserting
# against hooks.json broke when S-0.4 untracking landed; assertions
# against the registry are stable across the activate boundary.
#
# Source from a bats file:
#   load "${BATS_TEST_DIRNAME}/helpers/registry.bash"
#
# Usage:
#   registry_has_hook "validate-table-cell-count"
#   registry_has_hook "validate-input-hash" "PostToolUse"
#   registry_has_hook "protect-secrets" "PreToolUse" "Bash"
#
# All three forms return 0 (success) when the hook is registered with
# the requested specificity, non-zero otherwise. The registry path is
# resolved relative to BATS_TEST_DIRNAME for portability.

REGISTRY_PATH="${BATS_TEST_DIRNAME}/../hooks-registry.toml"

# Assert that a hook is registered. Optional event + tool match for
# tighter assertions.
#
# Args:
#   $1: hook name (required, e.g. "validate-input-hash")
#   $2: event (optional, e.g. "PostToolUse"). When omitted, name match alone passes.
#   $3: tool matcher (optional, e.g. "Bash" or "Edit|Write"). When set,
#       the entry must have a tool field that equals or contains the requested value.
registry_has_hook() {
  local name="$1"
  local want_event="${2:-}"
  local want_tool="${3:-}"

  awk -v name="$name" -v want_event="$want_event" -v want_tool="$want_tool" '
    /^\[\[hooks\]\]/      { in_block = 1; n = ""; e = ""; t = ""; next }
    in_block && /^name = /  { gsub(/"/, "", $3); n = $3; next }
    in_block && /^event = / { gsub(/"/, "", $3); e = $3; next }
    in_block && /^tool = /  { gsub(/"/, "", $3); t = $3; next }
    in_block && /^$/ {
      if (n == name) {
        if (want_event == "" || e == want_event) {
          if (want_tool == "" || t == want_tool || index(t, want_tool) > 0) {
            found = 1
            exit 0
          }
        }
      }
      in_block = 0
    }
    END { exit !found }
  ' "$REGISTRY_PATH"
}

# Assert that a script_path is registered (for legacy bash hooks routed
# through legacy-bash-adapter.wasm). Used by tests that previously
# greped for `.sh` references in hooks.json.
#
# Args:
#   $1: script path relative to plugin root (e.g. "hooks/validate-input-hash.sh")
registry_has_script() {
  local script="$1"
  grep -qF "script_path = \"$script\"" "$REGISTRY_PATH"
}
