/**
 * Playwright Demo Evidence Template — Dark Factory
 *
 * Generated by demo-recorder agent from acceptance criteria.
 * Records video + screenshots as demo evidence for web/UI products.
 *
 * Best Practices:
 * - ONE test per acceptance criterion — name matches AC-NNN
 * - Use slowMo (200ms) for readable demo recordings
 * - Use video: 'on' to always record (not 'on-first-retry')
 * - Take screenshots at key verification points, not just on failure
 * - Use data-testid locators for stability, not CSS selectors
 * - Every test records BOTH success AND error path
 * - Keep recordings under 15 seconds per AC
 * - Viewport: 1280x720 for consistent PR rendering
 *
 * Usage:
 *   npx playwright test docs/demo-evidence/AC-NNN-description.spec.ts
 *
 * Output:
 *   docs/demo-evidence/AC-NNN-description.webm  (video)
 *   docs/demo-evidence/AC-NNN-description.png   (screenshot)
 */

import { test, expect } from '@playwright/test';

// === Factory-Standard Config ===
// These settings should match playwright.config.ts for the project.
// If running standalone, configure via the test.use() block below.
test.use({
  // Video: always record for demo evidence
  video: {
    mode: 'on',
    size: { width: 1280, height: 720 },
  },
  // Screenshots at key points
  screenshot: 'on',
  // Slow motion for readable demos — viewer can see each action
  launchOptions: {
    slowMo: 200,
  },
  // Consistent viewport
  viewport: { width: 1280, height: 720 },
  // Trace for debugging (optional — remove in CI if too large)
  trace: 'retain-on-failure',
});

// === Demo: {ac_id} — {ac_description} ===
test('{ac_id}: {ac_description} (success path)', async ({ page }) => {
  // Navigate to the application
  await page.goto('http://localhost:{port}');

  // Wait for the page to be ready
  await expect(page.getByTestId('{ready_indicator}')).toBeVisible();

  // Screenshot: initial state
  await page.screenshot({
    path: 'docs/demo-evidence/{ac_id}-01-initial.png',
    fullPage: true,
  });

  // Perform the action being demonstrated
  // await page.getByTestId('{action_element}').click();
  // await page.getByTestId('{input_element}').fill('{test_input}');
  // await page.getByTestId('{submit_button}').click();

  // Wait for the expected result
  // await expect(page.getByTestId('{result_element}')).toContainText('{expected_text}');

  // Screenshot: result state
  await page.screenshot({
    path: 'docs/demo-evidence/{ac_id}-02-result.png',
    fullPage: true,
  });
});

test('{ac_id}: {ac_description} (error path)', async ({ page }) => {
  await page.goto('http://localhost:{port}');
  await expect(page.getByTestId('{ready_indicator}')).toBeVisible();

  // Perform an invalid action to trigger the error path
  // await page.getByTestId('{input_element}').fill('{invalid_input}');
  // await page.getByTestId('{submit_button}').click();

  // Verify the error is displayed correctly
  // await expect(page.getByTestId('{error_element}')).toBeVisible();
  // await expect(page.getByTestId('{error_element}')).toContainText('{expected_error}');

  // Screenshot: error state
  await page.screenshot({
    path: 'docs/demo-evidence/{ac_id}-03-error.png',
    fullPage: true,
  });
});
