//! block-ai-attribution — PreToolUse gate hook.
//!
//! Blocks `git commit` commands whose message contains AI attribution patterns.
//!
//! Pattern set (canonical, from bash predecessor + spec TV-001..011):
//!   TV-001: Co-Authored-By: Claude
//!   TV-002: Co-Authored-By: Anthropic
//!   TV-003: Co-Authored-By: GPT
//!   TV-004: Co-Authored-By: OpenAI
//!   TV-005: Co-Authored-By: Gemini
//!   TV-006: Co-Authored-By: Google AI
//!   TV-007: Generated with Claude Code
//!   TV-008: Generated by Claude
//!   TV-009: Generated by AI
//!   TV-010: noreply@anthropic.com
//!   TV-011: noreply@openai.com

use vsdd_hook_sdk::{HookPayload, HookResult};

/// AI vendor names that trigger a Co-Authored-By block.
///
/// Matched case-insensitively against the text that follows
/// `co-authored-by:` (with any amount of whitespace between the
/// colon and the name).
const COAUTHORED_AI_NAMES: &[&str] = &[
    "claude",
    "anthropic",
    "gpt",
    "openai",
    "gemini",
    "google ai",
];

/// Exact phrases matched case-insensitively anywhere in the command string.
/// Each entry is (pattern_lower, human_readable_label).
const PHRASE_PATTERNS: &[(&str, &str)] = &[
    ("generated with claude code", "Generated with Claude Code"),
    ("generated by claude", "Generated by Claude"),
    ("generated by ai", "Generated by AI"),
    ("noreply@anthropic.com", "noreply@anthropic.com"),
    ("noreply@openai.com", "noreply@openai.com"),
];

/// Detect the first AI attribution pattern in `command`, returning a
/// human-readable description of the matched pattern, or `None` if clean.
///
/// Pure-core function — no I/O, no side effects (BC-4.05.004 candidate).
pub fn detect_attribution(command: &str) -> Option<String> {
    let lower = command.to_lowercase();

    // --- Co-Authored-By: <AI name> ---
    // Find every occurrence of "co-authored-by:" and check whether the text
    // that follows (after optional whitespace) starts with one of the AI names.
    let coauthor_marker = "co-authored-by:";
    let mut search_from = 0;
    while let Some(pos) = lower[search_from..].find(coauthor_marker) {
        let abs_pos = search_from + pos;
        let after_colon = lower[abs_pos + coauthor_marker.len()..].trim_start();
        for ai_name in COAUTHORED_AI_NAMES {
            if after_colon.starts_with(ai_name) {
                return Some(format!(
                    "AI attribution detected: Co-Authored-By: {}",
                    ai_name
                ));
            }
        }
        search_from = abs_pos + coauthor_marker.len();
    }

    // --- Phrase patterns (Generated with/by, email addresses) ---
    for (pattern, label) in PHRASE_PATTERNS {
        if lower.contains(pattern) {
            return Some(format!("AI attribution detected: {}", label));
        }
    }

    None
}

/// PreToolUse entry point.
///
/// Returns `HookResult::Block` when the Bash command is a `git commit`
/// containing an AI attribution pattern.  Returns `HookResult::Continue`
/// for all other commands or attribution-free commits.
pub fn on_hook_logic(payload: HookPayload) -> HookResult {
    // Only inspect Bash tool invocations.
    if payload.tool_name != "Bash" {
        return HookResult::Continue;
    }

    // Extract tool_input.command; if missing, it is safe to continue.
    let command = match payload.tool_input.get("command").and_then(|v| v.as_str()) {
        Some(cmd) => cmd.to_owned(),
        None => return HookResult::Continue,
    };

    // Only gate on git commit commands.
    if !command.contains("git commit") {
        return HookResult::Continue;
    }

    // Scan for attribution patterns.
    match detect_attribution(&command) {
        Some(reason) => HookResult::block(reason),
        None => HookResult::Continue,
    }
}

// WASM export — the #[hook] macro wires this in production builds.
// Tests call `on_hook_logic` directly to stay in-process.
// `on_hook` is invoked by the WASM runtime via the exported symbol; the
// compiler cannot see that call site, hence the allow.
#[cfg(not(test))]
#[allow(dead_code)]
mod wasm_entry {
    use vsdd_hook_sdk::hook;
    use vsdd_hook_sdk::{HookPayload, HookResult};

    #[hook]
    pub fn on_hook(payload: HookPayload) -> HookResult {
        super::on_hook_logic(payload)
    }
}
