//! block-ai-attribution — PreToolUse gate hook (stub).
//!
//! Blocks `git commit` commands whose message contains AI attribution patterns.
//! Real implementation arrives in the GREEN phase of S-3.03.
//!
//! Pattern set (from bash predecessor + spec):
//!   - Co-Authored-By: Claude / Anthropic / GPT / OpenAI / Gemini / Google AI
//!   - "Generated with Claude Code"
//!   - "Generated by Claude"
//!   - "Generated by AI"
//!   - noreply@anthropic.com
//!   - noreply@openai.com

use vsdd_hook_sdk::{HookPayload, HookResult};

/// Detect the first AI attribution pattern in `command`, returning a
/// human-readable description of the matched pattern, or `None` if clean.
///
/// Pure-core function — no I/O, no side effects (BC-4.05.004 candidate).
pub fn detect_attribution(command: &str) -> Option<String> {
    unimplemented!("S-3.03 GREEN: implement attribution pattern detection")
}

/// PreToolUse entry point.
///
/// Returns `HookResult::Block` when the Bash command is a `git commit`
/// containing an AI attribution pattern.  Returns `HookResult::Continue`
/// for all other commands or attribution-free commits.
pub fn on_hook_logic(payload: HookPayload) -> HookResult {
    unimplemented!("S-3.03 GREEN: implement on_hook_logic")
}

// WASM export — the #[hook] macro wires this in production builds.
// Tests call `on_hook_logic` directly to stay in-process.
#[cfg(not(test))]
mod wasm_entry {
    use vsdd_hook_sdk::hook;
    use vsdd_hook_sdk::{HookPayload, HookResult};

    #[hook]
    pub fn on_hook(payload: HookPayload) -> HookResult {
        super::on_hook_logic(payload)
    }
}
