//! Red Gate unit tests for validate-heavy-op-delegation.
//!
//! Generated by stub-architect for S-18.06. Every test in this file maps to an
//! acceptance criterion in S-18.06 and a postcondition or invariant in
//! BC-4.15.001. All tests exercise `evaluate_patterns` and/or
//! `truncate_command_preview` via `todo!()` stub bodies and MUST FAIL until
//! the implementer fills in the real logic.
//!
//! # Red Gate Test Table (S-18.06 v1.5 — unit.rs subset)
//!
//! | Test name | AC | BC clause | Red Gate state |
//! |-----------|----|-----------|-|
//! | `test_heavy_op_gate_first_match_semantics_single_advisory` | AC-005 | INV3 | RED (todo!) |
//! | `test_heavy_op_gate_truncates_command_preview_at_120_chars` | AC-006 | INV4 | RED (todo!) |
//! | `test_heavy_op_gate_no_truncation_on_short_command` | AC-006 | INV4 | RED (todo!) |
//! | `test_heavy_op_gate_empty_pattern_list_no_emission` | AC-011 | EC-012 | RED (todo!) |
//! | `test_heavy_op_gate_always_returns_continue_on_match` | AC-004 | INV2 | RED (todo!) |
//!
//! Red Gate minimum: 5 Rust unit tests (this file) + 7 bats tests
//! (validate-heavy-op-delegation.bats) = 12 total. All must fail before any
//! real Rust crate source is authored (S-18.06 T-1 / Red Gate Plan).
//!
//! BC-5.38.005 Self-Check Rule applied to every function below:
//! "If I include this real implementation, will the test for this function pass
//! trivially without any implementer work?"
//! Answer for all 5 tests: YES — the bodies call into `evaluate_patterns` and
//! `truncate_command_preview`, both of which are `todo!()` stubs. Therefore
//! all test bodies trigger the Red Gate via the `todo!()` panic.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use validate_heavy_op_delegation::{
    DEFAULT_PATTERNS, GateResult, evaluate_patterns, truncate_command_preview,
    COMMAND_PREVIEW_MAX_CHARS, ELLIPSIS,
};

// ---------------------------------------------------------------------------
// AC-005 — First-match semantics; exactly one advisory per invocation (INV3)
// ---------------------------------------------------------------------------

/// AC-005 / INV3: when multiple patterns from the configured list would match
/// the same command string, the gate stops at the FIRST matching pattern and
/// emits exactly ONE `DelegationRecommended` advisory. Subsequent patterns are
/// not evaluated after a match.
///
/// Setup: Bash command `grep -r TODO . | grep -R FIXME`. Both `grep -r` and
/// `grep -R` are in the default pattern list. `grep -r` appears BEFORE `grep -R`
/// in the list declaration order.
///
/// Assert: `evaluate_patterns` returns `GateResult::Advisory` (not Continue);
/// `matched_pattern` is `"grep -r"` (the first match in list order, not `"grep -R"`).
///
/// Red Gate: panics at todo!() in evaluate_patterns.
#[test]
fn test_heavy_op_gate_first_match_semantics_single_advisory() {
    let command = "grep -r TODO . | grep -R FIXME";
    let result = evaluate_patterns(command, DEFAULT_PATTERNS);

    // Must produce an advisory (first match found).
    assert!(
        matches!(result, GateResult::Advisory(_)),
        "AC-005/INV3: command matching multiple patterns must produce Advisory (first-match), \
        got: {result:?}"
    );

    // The matched_pattern must be "grep -r" (first in list order, not "grep -R").
    if let GateResult::Advisory(ref advisory) = result {
        assert_eq!(
            advisory.matched_pattern, "grep -r",
            "AC-005/INV3: matched_pattern must be \"grep -r\" (first match in list order); \
            \"grep -R\" appears later in the list and must NOT be the first match. \
            Got: {:?}",
            advisory.matched_pattern
        );
    }
}

// ---------------------------------------------------------------------------
// AC-006 — command_preview ≤120-char truncation invariant (INV4)
// ---------------------------------------------------------------------------

/// AC-006 / INV4: when a Bash command exceeds 120 Unicode code points, the
/// `command_preview` MUST be the first 120 code points followed by U+2026
/// (ELLIPSIS), yielding a (COMMAND_PREVIEW_MAX_CHARS + 1)-code-point string.
///
/// Setup: Bash command of 200 characters containing `grep -r` (to ensure a
/// match is found when evaluated, but here we test `truncate_command_preview`
/// directly).
///
/// Assert: `truncate_command_preview` returns a string of exactly 121 code
/// points; the final code point is U+2026; the first 120 code points match the
/// first 120 code points of the input.
///
/// Red Gate: panics at todo!() in truncate_command_preview.
#[test]
fn test_heavy_op_gate_truncates_command_preview_at_120_chars() {
    // Build a 200-char command string containing "grep -r".
    let base = "grep -r TODO ";
    let padding: String = "x".repeat(200 - base.len());
    let command = format!("{base}{padding}");
    assert_eq!(
        command.chars().count(),
        200,
        "test fixture must be exactly 200 code points"
    );

    let preview = truncate_command_preview(&command);

    // Assert: exactly COMMAND_PREVIEW_MAX_CHARS + 1 code points (120 + ellipsis).
    let preview_len = preview.chars().count();
    assert_eq!(
        preview_len,
        COMMAND_PREVIEW_MAX_CHARS + 1,
        "AC-006/INV4: preview of a 200-char command must be exactly {} code points \
        ({} chars + U+2026), got {} code points. Preview: {:?}",
        COMMAND_PREVIEW_MAX_CHARS + 1,
        COMMAND_PREVIEW_MAX_CHARS,
        preview_len,
        preview
    );

    // Assert: final code point is U+2026.
    let last_char = preview.chars().last().expect("preview must be non-empty");
    assert_eq!(
        last_char, ELLIPSIS,
        "AC-006/INV4: final code point of truncated preview must be U+2026 (…), \
        got: {:?}",
        last_char
    );

    // Assert: first COMMAND_PREVIEW_MAX_CHARS code points match the input.
    let expected_prefix: String = command.chars().take(COMMAND_PREVIEW_MAX_CHARS).collect();
    let actual_prefix: String = preview.chars().take(COMMAND_PREVIEW_MAX_CHARS).collect();
    assert_eq!(
        actual_prefix, expected_prefix,
        "AC-006/INV4: first {} code points of preview must match the input command",
        COMMAND_PREVIEW_MAX_CHARS
    );
}

/// AC-006 / INV4: when a Bash command is ≤120 Unicode code points, the
/// `command_preview` MUST equal the full command string with NO truncation
/// and NO ellipsis appended.
///
/// Setup: Bash command `grep -r .` (9 characters; well under 120).
///
/// Assert: `truncate_command_preview` returns the full command string unchanged;
/// the return value does NOT end with U+2026.
///
/// Red Gate: panics at todo!() in truncate_command_preview.
#[test]
fn test_heavy_op_gate_no_truncation_on_short_command() {
    let command = "grep -r .";
    assert!(
        command.chars().count() <= COMMAND_PREVIEW_MAX_CHARS,
        "test fixture must be ≤{} code points", COMMAND_PREVIEW_MAX_CHARS
    );

    let preview = truncate_command_preview(command);

    // Assert: preview equals the full command string (no truncation).
    assert_eq!(
        preview, command,
        "AC-006/INV4: short command preview must equal full command string (no truncation); \
        got: {:?}",
        preview
    );

    // Assert: no ellipsis appended.
    let last_char = preview.chars().last();
    assert_ne!(
        last_char,
        Some(ELLIPSIS),
        "AC-006/INV4: short command preview must NOT end with U+2026 (…); \
        got last char: {:?}",
        last_char
    );
}

// ---------------------------------------------------------------------------
// AC-011 — Empty patterns list: no emission on any Bash command (EC-012)
// ---------------------------------------------------------------------------

/// AC-011 / EC-012: when the patterns list is empty (`patterns = []`), no
/// pattern can ever match. ALL Bash commands must pass silently (PC-A);
/// no advisory emitted for any command.
///
/// Setup: patterns list `[]` (empty); Bash command `cargo test --release
/// --workspace` (would normally match the default pattern list).
///
/// Assert: `evaluate_patterns` returns `GateResult::Continue` (not Advisory).
///
/// Red Gate: panics at todo!() in evaluate_patterns.
#[test]
fn test_heavy_op_gate_empty_pattern_list_no_emission() {
    let command = "cargo test --release --workspace";
    let patterns: &[&str] = &[]; // empty pattern list

    let result = evaluate_patterns(command, patterns);

    assert_eq!(
        result,
        GateResult::Continue,
        "AC-011/EC-012: empty pattern list must return Continue for any command; \
        no advisory must be emitted. Command: {:?}. Got: {result:?}",
        command
    );
}

// ---------------------------------------------------------------------------
// AC-004 — Gate always returns Continue on match (INV2)
// ---------------------------------------------------------------------------

/// AC-004 / INV2: the gate MUST return Continue (block_intent = false) even
/// when a pattern matches. Setting block_intent = true is a specification
/// violation.
///
/// This test drives `evaluate_patterns` directly to verify that a match result
/// is `GateResult::Advisory` (Continue+advisory), NOT a blocking result. The
/// `GateResult` enum has no Block variant — its absence in the type system is
/// the static enforcement of INV2. This test additionally checks that:
/// (a) a match is found (Advisory is returned, not Continue), and
/// (b) the advisory carries the expected matched_pattern (not block_intent).
///
/// Red Gate: panics at todo!() in evaluate_patterns.
#[test]
fn test_heavy_op_gate_always_returns_continue_on_match() {
    // Test vector from BC-4.15.001 §Canonical Test Vectors:
    // "cargo test --release" → Continue + DelegationRecommended advisory.
    let command = "cargo test --release";
    let result = evaluate_patterns(command, DEFAULT_PATTERNS);

    // Must produce Advisory (not Continue — the pattern DOES match).
    // The absence of a GateResult::Block variant statically enforces INV2.
    assert!(
        matches!(result, GateResult::Advisory(_)),
        "AC-004/INV2: 'cargo test --release' must match default patterns and return \
        GateResult::Advisory (Continue+advisory, never Block). Got: {result:?}"
    );

    // The matched_pattern must be "cargo test --release" (exact first match).
    if let GateResult::Advisory(ref advisory) = result {
        assert_eq!(
            advisory.matched_pattern, "cargo test --release",
            "AC-004/INV2: matched_pattern must be \"cargo test --release\". \
            Got: {:?}",
            advisory.matched_pattern
        );

        // command_preview must satisfy the truncation invariant (INV4):
        // "cargo test --release" is well under 120 chars — no truncation expected.
        assert_eq!(
            advisory.command_preview, command,
            "AC-004/INV4: short command preview must equal full command (no truncation). \
            Got: {:?}",
            advisory.command_preview
        );
    }
}
