//! Macros for resolver authoring.
//!
//! Provides the implementation logic for the `#[resolver]` proc-macro (declared in
//! crate root `lib.rs` per Rust's proc-macro crate restriction).
//! Parallel to `#[hook]` for hook plugins. Per BC-4.12.002 PC5 and ADR-018.

use proc_macro::TokenStream;
use proc_macro2::{Span, TokenStream as TokenStream2};
use quote::quote;
use syn::{ItemFn, ReturnType, Type, parse_macro_input};

const SIGNATURE_HELP: &str = "#[resolver] expects exactly one argument of type `ResolverInput`; \
     `resolve_impl` must have signature \
     `fn resolve_impl(input: ResolverInput) -> ResolverOutput`";

/// Implementation backing the `#[resolver]` proc-macro attribute (declared in crate root).
///
/// The annotated function MUST be named `resolve_impl` and MUST have the exact
/// signature `fn resolve_impl(input: ResolverInput) -> ResolverOutput`.
///
/// The macro generates a `pub extern "C" fn resolve(input_ptr: i32, input_len: i32) -> i64`
/// WASM export that:
///
/// 1. Reads the input byte slice from WASM linear memory at `input_ptr..input_ptr+input_len`.
/// 2. Deserializes the bytes from JSON into `ResolverInput`.
/// 3. Calls the user's `resolve_impl` function.
/// 4. Serializes the `ResolverOutput` to JSON bytes.
/// 5. Writes the output bytes to a WASM memory allocation.
/// 6. Returns the packed ptr+len pair: `((ptr as i64) << 32) | (len as i64)`.
///
/// Applying this macro to a function with the wrong name or wrong signature emits a
/// compile-time error. (BC-4.12.002 PC5)
pub fn resolver_impl(args: TokenStream, input: TokenStream) -> TokenStream {
    let user_fn = parse_macro_input!(input as ItemFn);

    if let Err(err) = validate_resolver_signature(&user_fn, args.into()) {
        // Emit the validation error. Also emit `fn main() {}` so the binary
        // crate doesn't produce a spurious "main function not found" secondary
        // error that would obscure the actionable diagnostic.
        let err_tokens = err.to_compile_error();
        let out: TokenStream2 = quote! {
            #err_tokens
            fn main() {}
        };
        return out.into();
    }

    let user_ident = &user_fn.sig.ident;

    let expanded: TokenStream2 = quote! {
        #user_fn

        /// WASM resolver entrypoint — generated by `#[resolver]` macro.
        ///
        /// Only emitted when compiling for `wasm32` targets (BC-4.12.002 PC1).
        /// On non-wasm32 hosts this block is compiled out entirely, enforcing that
        /// the packed-pointer ABI is only used on targets where pointers are 32-bit.
        ///
        /// Per BC-4.12.002 PC1/PC5: signature is `resolve(input_ptr: i32, input_len: i32) -> i64`.
        /// Return value is packed as `((output_ptr as i64) << 32) | (output_len as i64)`.
        ///
        /// Memory layout:
        /// - Input: byte slice in WASM linear memory at [input_ptr, input_ptr + input_len).
        /// - Output: JSON bytes allocated via `Vec<u8>` leaked into WASM linear memory;
        ///   caller (dispatcher) is responsible for reading before the module exits.
        #[cfg(target_arch = "wasm32")]
        #[unsafe(no_mangle)]
        pub extern "C" fn resolve(input_ptr: i32, input_len: i32) -> i64 {
            // SAFETY: The dispatcher passes a valid ptr+len into WASM linear memory.
            // The slice lives for the duration of this call.
            let input_bytes: &[u8] = unsafe {
                ::std::slice::from_raw_parts(input_ptr as *const u8, input_len as usize)
            };

            let resolver_input: ::vsdd_hook_sdk::resolver::ResolverInput =
                ::serde_json::from_slice(input_bytes)
                    .expect("resolver: failed to deserialize ResolverInput from dispatcher");

            let resolver_output = #user_ident(resolver_input);

            let output_bytes: Vec<u8> = ::serde_json::to_vec(&resolver_output)
                .expect("resolver: failed to serialize ResolverOutput");

            let output_len = output_bytes.len();
            // Leak the Vec so it stays alive after this function returns.
            // The dispatcher reads the bytes before the WASM instance exits.
            // SAFETY: On wasm32, pointers are 32-bit; the cast to i64 zero-extends
            // and the upper 32 bits are zero, making the pack `(ptr << 32) | len` correct.
            let output_ptr = output_bytes.leak().as_ptr() as i64;

            (output_ptr << 32) | (output_len as i64)
        }

        /// No-op main required for compilation as a binary crate (e.g., trybuild tests).
        /// Not invoked at runtime — resolver dispatch goes through `resolve()`.
        fn main() {}
    };

    expanded.into()
}

/// Validates that the annotated function has the exact resolver signature.
///
/// Requirements (BC-4.12.002 PC5):
/// - Exactly one parameter (the ResolverInput)
/// - Return type last segment must be `ResolverOutput`
///
/// The `call_site_args` token stream carries the span of the `#[resolver]` attribute
/// invocation itself, which is used to anchor the error diagnostic to the attribute
/// rather than the function body (matching the expected stderr in tests/ui/wrong_sig.stderr).
fn validate_resolver_signature(f: &ItemFn, call_site_args: TokenStream2) -> Result<(), syn::Error> {
    // The attribute span: if args are present use their span; otherwise fall back
    // to proc_macro2::Span::call_site() which maps to the `#[resolver]` invocation.
    let attr_span = if call_site_args.is_empty() {
        Span::call_site()
    } else {
        call_site_args
            .into_iter()
            .next()
            .map(|t| t.span())
            .unwrap_or_else(Span::call_site)
    };

    // Validate: exactly one argument
    if f.sig.inputs.len() != 1 {
        return Err(syn::Error::new(attr_span, SIGNATURE_HELP));
    }

    // Validate: return type must be ResolverOutput
    match &f.sig.output {
        ReturnType::Default => {
            return Err(syn::Error::new(attr_span, SIGNATURE_HELP));
        }
        ReturnType::Type(_, ty) => {
            if !is_resolver_output_type(ty) {
                return Err(syn::Error::new(attr_span, SIGNATURE_HELP));
            }
        }
    }

    Ok(())
}

fn is_resolver_output_type(ty: &Type) -> bool {
    if let Type::Path(p) = ty
        && let Some(last) = p.path.segments.last()
    {
        return last.ident == "ResolverOutput";
    }
    false
}
