//! Tests verifying that every canonical AI attribution pattern triggers Block.
//!
//! BC-4.05.001 (v1.1 candidate): detect_attribution returns the matched pattern
//! for each AI attribution marker defined in the bash predecessor and spec.
//!
//! Each test maps to a distinct pattern from the bash hook's grep regexes and
//! the CAP-008 attribution injection list.
//!
//! Test vector source: block-ai-attribution.sh (grep -iE patterns).

use block_ai_attribution::detect_attribution;

// ---------------------------------------------------------------------------
// Co-Authored-By variants (BC-4.05.001)
// ---------------------------------------------------------------------------

/// TV-001: Co-Authored-By: Claude
#[test]
fn test_TV_001_coauthored_by_claude_is_detected() {
    let cmd = "git commit -m \"fix\n\nCo-Authored-By: Claude <noreply@anthropic.com>\"";
    let result = detect_attribution(cmd);
    assert!(
        result.is_some(),
        "Co-Authored-By: Claude must be detected; got None"
    );
}

/// TV-002: Co-Authored-By: Anthropic (variant without Claude name)
#[test]
fn test_TV_002_coauthored_by_anthropic_is_detected() {
    let cmd = "git commit -m \"fix\n\nCo-Authored-By: Anthropic Bot <bot@anthropic.com>\"";
    let result = detect_attribution(cmd);
    assert!(
        result.is_some(),
        "Co-Authored-By: Anthropic must be detected; got None"
    );
}

/// TV-003: Co-Authored-By: GPT
#[test]
fn test_TV_003_coauthored_by_gpt_is_detected() {
    let cmd = "git commit -m \"fix\n\nCo-Authored-By: GPT-4 <noreply@openai.com>\"";
    let result = detect_attribution(cmd);
    assert!(
        result.is_some(),
        "Co-Authored-By: GPT must be detected; got None"
    );
}

/// TV-004: Co-Authored-By: OpenAI
#[test]
fn test_TV_004_coauthored_by_openai_is_detected() {
    let cmd = "git commit -m \"fix\n\nCo-Authored-By: OpenAI <noreply@openai.com>\"";
    let result = detect_attribution(cmd);
    assert!(
        result.is_some(),
        "Co-Authored-By: OpenAI must be detected; got None"
    );
}

/// TV-005: Co-Authored-By: Gemini
#[test]
fn test_TV_005_coauthored_by_gemini_is_detected() {
    let cmd = "git commit -m \"fix\n\nCo-Authored-By: Gemini <noreply@google.com>\"";
    let result = detect_attribution(cmd);
    assert!(
        result.is_some(),
        "Co-Authored-By: Gemini must be detected; got None"
    );
}

/// TV-006: Co-Authored-By: Google AI
#[test]
fn test_TV_006_coauthored_by_google_ai_is_detected() {
    let cmd = "git commit -m \"fix\n\nCo-Authored-By: Google AI <noreply@google.com>\"";
    let result = detect_attribution(cmd);
    assert!(
        result.is_some(),
        "Co-Authored-By: Google AI must be detected; got None"
    );
}

// ---------------------------------------------------------------------------
// Generated-by attribution variants (BC-4.05.001)
// ---------------------------------------------------------------------------

/// TV-007: "Generated with Claude Code"
#[test]
fn test_TV_007_generated_with_claude_code_is_detected() {
    let cmd = "git commit -m \"fix\n\n🤖 Generated with Claude Code\"";
    let result = detect_attribution(cmd);
    assert!(
        result.is_some(),
        "'Generated with Claude Code' must be detected; got None"
    );
}

/// TV-008: "Generated by Claude"
#[test]
fn test_TV_008_generated_by_claude_is_detected() {
    let cmd = "git commit -m \"fix\n\nGenerated by Claude\"";
    let result = detect_attribution(cmd);
    assert!(
        result.is_some(),
        "'Generated by Claude' must be detected; got None"
    );
}

/// TV-009: "Generated by AI"
#[test]
fn test_TV_009_generated_by_ai_is_detected() {
    let cmd = "git commit -m \"fix\n\nGenerated by AI\"";
    let result = detect_attribution(cmd);
    assert!(
        result.is_some(),
        "'Generated by AI' must be detected; got None"
    );
}

// ---------------------------------------------------------------------------
// Email address patterns (BC-4.05.001)
// ---------------------------------------------------------------------------

/// TV-010: noreply@anthropic.com
#[test]
fn test_TV_010_noreply_anthropic_email_is_detected() {
    let cmd = "git commit -m \"fix\n\nSigned-off-by: Claude <noreply@anthropic.com>\"";
    let result = detect_attribution(cmd);
    assert!(
        result.is_some(),
        "noreply@anthropic.com must be detected; got None"
    );
}

/// TV-011: noreply@openai.com
#[test]
fn test_TV_011_noreply_openai_email_is_detected() {
    let cmd = "git commit -m \"fix\n\nSigned-off-by: GPT <noreply@openai.com>\"";
    let result = detect_attribution(cmd);
    assert!(
        result.is_some(),
        "noreply@openai.com must be detected; got None"
    );
}

// ---------------------------------------------------------------------------
// detect_attribution returns matched pattern text (BC-4.05.001)
// ---------------------------------------------------------------------------

/// BC-4.05.001: detect_attribution returns Some(matched_text) — the returned
/// string must be non-empty and describe the match.
#[test]
fn test_BC_4_05_001_detect_attribution_returns_matched_text() {
    let cmd = "git commit -m \"fix\n\nCo-Authored-By: Claude <noreply@anthropic.com>\"";
    let matched = detect_attribution(cmd).expect("must return Some");
    assert!(
        !matched.is_empty(),
        "matched pattern string must be non-empty"
    );
}

/// BC-4.05.002: detect_attribution returns None for clean commit message.
#[test]
fn test_BC_4_05_002_detect_attribution_returns_none_for_clean_commit() {
    let cmd = "git commit -m \"fix: correct off-by-one in loop\"";
    let result = detect_attribution(cmd);
    assert!(
        result.is_none(),
        "attribution-free commit must return None; got {result:?}"
    );
}

/// BC-4.05.004: detect_attribution is callable with no payload context —
/// confirms pure-core interface (no I/O, just string in / Option<String> out).
#[test]
fn test_BC_4_05_004_detect_attribution_is_pure_function() {
    // Calling it twice with the same input must return the same result.
    let cmd = "git commit -m \"fix\n\nCo-Authored-By: Claude <x@anthropic.com>\"";
    let a = detect_attribution(cmd);
    let b = detect_attribution(cmd);
    assert_eq!(a, b, "pure function must be deterministic");
}
