//! Edge case tests per spec EC table and common attribution bypass attempts.
//!
//! EC-002: `git commit --allow-empty` with attribution → Block.
//! EC-003: Attribution in commit body (not subject line) → Block.
//! Additional: case-insensitivity, whitespace variants, embedded patterns,
//! partial matches that must NOT match.

use block_ai_attribution::{detect_attribution, on_hook_logic};
use vsdd_hook_sdk::{HookPayload, HookResult};

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

fn bash_payload(command: &str) -> HookPayload {
    let json = serde_json::json!({
        "event_name": "PreToolUse",
        "tool_name": "Bash",
        "session_id": "sess-ec",
        "dispatcher_trace_id": "trace-ec",
        "tool_input": { "command": command }
    });
    serde_json::from_value(json).expect("fixture must deserialize")
}

fn assert_block(result: HookResult, label: &str) {
    match result {
        HookResult::Block { .. } => {}
        other => panic!("{label}: expected Block, got {other:?}"),
    }
}

fn assert_continue(result: HookResult, label: &str) {
    match result {
        HookResult::Continue => {}
        other => panic!("{label}: expected Continue, got {other:?}"),
    }
}

// ---------------------------------------------------------------------------
// EC-002: git commit --allow-empty with attribution
// ---------------------------------------------------------------------------

/// EC-002: `git commit --allow-empty` + Co-Authored-By: Claude → Block.
#[test]
fn test_BC_4_05_003_ec002_allow_empty_with_coauthored_by_claude_is_blocked() {
    let cmd = "git commit --allow-empty -m \"chore: placeholder\n\nCo-Authored-By: Claude <noreply@anthropic.com>\"";
    let result = on_hook_logic(bash_payload(cmd));
    assert_block(
        result,
        "git commit --allow-empty with Co-Authored-By: Claude",
    );
}

/// EC-002: `git commit --allow-empty` + Generated with Claude Code → Block.
#[test]
fn test_BC_4_05_003_ec002_allow_empty_with_generated_with_claude_code_is_blocked() {
    let cmd = "git commit --allow-empty -m \"chore: placeholder\n\n🤖 Generated with Claude Code\"";
    let result = on_hook_logic(bash_payload(cmd));
    assert_block(
        result,
        "git commit --allow-empty with Generated with Claude Code",
    );
}

// ---------------------------------------------------------------------------
// EC-003: Attribution in commit body, not subject line
// ---------------------------------------------------------------------------

/// EC-003: Attribution only in body paragraph (not the first line) → Block.
#[test]
fn test_BC_4_05_003_ec003_attribution_in_body_not_subject_is_blocked() {
    let cmd = concat!(
        "git commit -m \"fix: correct panic in parser\n\n",
        "This patch addresses the root cause.\n\n",
        "Co-Authored-By: Claude <noreply@anthropic.com>\""
    );
    let result = on_hook_logic(bash_payload(cmd));
    assert_block(result, "attribution buried in commit body");
}

/// EC-003: `Generated by AI` in body only → Block.
#[test]
fn test_BC_4_05_003_ec003_generated_by_ai_in_body_is_blocked() {
    let cmd = "git commit -m \"docs: update readme\n\nContent generated by AI for review.\"";
    let result = on_hook_logic(bash_payload(cmd));
    assert_block(result, "Generated by AI in body");
}

// ---------------------------------------------------------------------------
// Case-insensitivity
// ---------------------------------------------------------------------------

/// Pattern matching must be case-insensitive: all-caps variant.
#[test]
fn test_TV_EC_case_insensitive_uppercase_coauthored() {
    let cmd = "git commit -m \"fix\n\nCO-AUTHORED-BY: CLAUDE <NOREPLY@ANTHROPIC.COM>\"";
    let result = detect_attribution(cmd);
    assert!(
        result.is_some(),
        "uppercase CO-AUTHORED-BY must be detected (case-insensitive match)"
    );
}

/// Pattern matching must be case-insensitive: mixed-case Generated.
#[test]
fn test_TV_EC_case_insensitive_mixed_case_generated_by_claude() {
    let cmd = "git commit -m \"fix\n\ngenerated BY claude\"";
    let result = detect_attribution(cmd);
    assert!(
        result.is_some(),
        "mixed-case 'generated BY claude' must be detected"
    );
}

// ---------------------------------------------------------------------------
// Whitespace / formatting variants
// ---------------------------------------------------------------------------

/// Extra spaces between Co-Authored-By: and the name.
#[test]
fn test_TV_EC_extra_spaces_in_coauthored_by() {
    let cmd = "git commit -m \"fix\n\nCo-Authored-By:   Claude  <noreply@anthropic.com>\"";
    let result = detect_attribution(cmd);
    assert!(
        result.is_some(),
        "extra spaces after Co-Authored-By: colon must still be detected"
    );
}

/// Pattern embedded mid-sentence in the body.
#[test]
fn test_TV_EC_pattern_embedded_mid_sentence() {
    let cmd = "git commit -m \"fix\n\nThis commit was reviewed; noreply@anthropic.com assisted.\"";
    let result = detect_attribution(cmd);
    assert!(
        result.is_some(),
        "noreply@anthropic.com embedded mid-sentence must be detected"
    );
}

// ---------------------------------------------------------------------------
// Near-miss strings that must NOT trigger Block
// ---------------------------------------------------------------------------

/// "co-author" (human co-author, not AI) must not match.
#[test]
fn test_TV_EC_human_coauthor_does_not_match() {
    let cmd =
        "git commit -m \"feat: pair programmed\n\nCo-Authored-By: Alice <alice@example.com>\"";
    let result = detect_attribution(cmd);
    assert!(
        result.is_none(),
        "human Co-Authored-By should not be flagged; got {result:?}"
    );
}

/// Word "generated" without AI context must not match.
#[test]
fn test_TV_EC_word_generated_alone_does_not_match() {
    let cmd = "git commit -m \"chore: generated migrations from schema\"";
    let result = detect_attribution(cmd);
    assert!(
        result.is_none(),
        "'generated' without AI context must not match; got {result:?}"
    );
}

/// "claude" as part of a human name that is not an AI tool attribution.
#[test]
fn test_TV_EC_human_name_claude_in_human_context_does_not_match() {
    // "Claude Debussy" — human composer, not AI tool attribution.
    // This is a gray area; spec says "Co-Authored-By: Claude" triggers.
    // A human named "Claude" without "Anthropic" context and NOT in Co-Authored-By:
    // form should NOT trigger. This confirms the pattern is anchored to the
    // Co-Authored-By header or explicit "Generated by/with" phrases.
    let cmd = "git commit -m \"chore: inspired by Claude Debussy's approach\"";
    let result = detect_attribution(cmd);
    assert!(
        result.is_none(),
        "human reference to 'Claude' (not in attribution context) must not match; got {result:?}"
    );
}

// ---------------------------------------------------------------------------
// on_hook_logic edge cases (full payload path)
// ---------------------------------------------------------------------------

/// EC-002 full payload path: Block result carries a reason mentioning the pattern.
#[test]
fn test_BC_4_05_003_block_reason_mentions_pattern_for_ec002() {
    let cmd =
        "git commit --allow-empty -m \"chore\n\nCo-Authored-By: Claude <noreply@anthropic.com>\"";
    let result = on_hook_logic(bash_payload(cmd));
    match result {
        HookResult::Block { reason } => {
            assert!(!reason.is_empty(), "Block reason must be non-empty");
        }
        other => panic!("Expected Block, got {other:?}"),
    }
}

/// `git commit -F file` pattern — if the command string contains -F,
/// the command itself is still inspected for inline attribution.
/// A -F invocation without inline attribution in the command string → Continue.
#[test]
fn test_TV_EC_git_commit_file_flag_without_inline_attribution_returns_continue() {
    let cmd = "git commit -F /tmp/commit-msg.txt";
    let result = on_hook_logic(bash_payload(cmd));
    assert_continue(
        result,
        "git commit -F with no inline attribution text in command",
    );
}
