#!/bin/bash
# block-ai-attribution.sh — PreToolUse hook on Bash
#
# Blocks git commit commands that contain AI attribution patterns:
#   - Co-Authored-By: Claude / Anthropic / GPT / OpenAI / Gemini / Google
#   - "Generated with Claude Code"
#   - "Generated by AI"
#   - noreply@anthropic.com / noreply@openai.com
#
# Trigger: PreToolUse on Bash tool invocations containing "git commit".
# Exit 0 on pass (no AI attribution found, or not a git commit).
# Exit 2 blocks the commit with instructions to remove the attribution.
#
# Deterministic, <100ms, no LLM.

set -euo pipefail

if ! command -v jq &>/dev/null; then
  exit 0
fi

INPUT=$(cat)
COMMAND=$(echo "$INPUT" | jq -r '.tool_input.command // empty')

# Only process git commit commands
case "$COMMAND" in
  *"git commit"*) ;;
  *) exit 0 ;;
esac

_emit() {
  if [ -n "${CLAUDE_PLUGIN_ROOT:-}" ] && [ -x "${CLAUDE_PLUGIN_ROOT}/bin/emit-event" ]; then
    "${CLAUDE_PLUGIN_ROOT}/bin/emit-event" "$@" 2>/dev/null || true
  fi
  return 0
}

block() {
  local reason="$1"
  local code="${2:-unknown}"
  _emit type=hook.block hook=block-ai-attribution matcher=Bash reason="$code" command="$COMMAND"
  echo "" >&2
  echo "AI ATTRIBUTION BLOCKED:" >&2
  echo "  $reason" >&2
  echo "  Remove the line and retry." >&2
  exit 2
}

# Check for AI attribution patterns (case-insensitive)
if echo "$COMMAND" | grep -qiE "Co-Authored-By:.*Claude|Co-Authored-By:.*Anthropic|Co-Authored-By:.*GPT|Co-Authored-By:.*OpenAI|Co-Authored-By:.*Gemini|Co-Authored-By:.*Google AI"; then
  block \
    "Commit message contains a Co-Authored-By line referencing an AI tool." \
    "ai_attribution_coauthored"
fi

if echo "$COMMAND" | grep -qiE "Generated with Claude Code|Generated by Claude|Generated by AI|noreply@anthropic\.com|noreply@openai\.com"; then
  block \
    "Commit message contains AI tool attribution text." \
    "ai_attribution_generated"
fi

exit 0
